version: 1.0.{build}
branches:
  only:
  - main
  - develop
image: Visual Studio 2022
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build_script:
- cmd: >-
    cd Resources/Deployment/Windows
    
    create_MemaMo-Installer.bat
artifacts:
- path: MemaMo*.exe
  name: Installer Binary
notifications:
- provider: Email
  to:
  - christianahrens@me.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false