version: 1.0.{build}
branches:
  only:
  - main
  - develop
image: macOS-Monterey
install:
- sh: >-
    cd "$APPVEYOR_BUILD_FOLDER"
    
    git submodule update --init --recursive
build_script:
- sh: >-
    cd Resources/Deployment/macOS

    chmod +rwx build_MenuBarMatrixMonitor.sh
    
    ./build_MenuBarMatrixMonitor.sh
notifications:
- provider: Email
  to:
  - christianahrens@me.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false