Mema: Mema::AudioSelectComponent Class Reference
Mema::AudioSelectComponent Class Reference
#include <AudioSelectComponent.h>
Classes
struct RelevantDeviceCharacteristics
Snapshot of the currently selected device's relevant characteristics used to detect changes.
Public Member Functions
AudioSelectComponent (juce::AudioDeviceManager *deviceManager, int minAudioInputChannels, int maxAudioInputChannels, int minAudioOutputChannels, int maxAudioOutputChannels, bool showMidiInputOptions, bool showMidiOutputSelector, bool showChannelsAsStereoPairs, bool hideAdvancedOptionsWithButton)
~AudioSelectComponent ()
void paint (juce::Graphics &) override
void resized () override
void visibilityChanged () override
Public Attributes
std::function< void()> onAudioDeviceChangedDuringAudioSelection
Protected Member Functions
void processAudioSelectionChanges ()
Detailed Description
component for selecting the audio input/output device and channel configuration.
Definition at line 27 of file AudioSelectComponent.h.
Constructor & Destructor Documentation
AudioSelectComponent()
Mema::AudioSelectComponent::AudioSelectComponent (juce::AudioDeviceManager * deviceManager, int minAudioInputChannels, int maxAudioInputChannels, int minAudioOutputChannels, int maxAudioOutputChannels, bool showMidiInputOptions, bool showMidiOutputSelector, bool showChannelsAsStereoPairs, bool hideAdvancedOptionsWithButton)
Definition at line 25 of file AudioSelectComponent.cpp.
~AudioSelectComponent()
Mema::AudioSelectComponent::~AudioSelectComponent ()
Definition at line 48 of file AudioSelectComponent.cpp.
Member Function Documentation
paint()
void Mema::AudioSelectComponent::paint (juce::Graphics &) override
Definition at line 63 of file AudioSelectComponent.cpp.
processAudioSelectionChanges()
void Mema::AudioSelectComponent::processAudioSelectionChanges () protected
Definition at line 52 of file AudioSelectComponent.cpp.
References onAudioDeviceChangedDuringAudioSelection.
Referenced by visibilityChanged().
resized()
void Mema::AudioSelectComponent::resized () override
Definition at line 73 of file AudioSelectComponent.cpp.
visibilityChanged()
void Mema::AudioSelectComponent::visibilityChanged () override
Definition at line 78 of file AudioSelectComponent.cpp.
References processAudioSelectionChanges().
Member Data Documentation
onAudioDeviceChangedDuringAudioSelection
std::function<void()> Mema::AudioSelectComponent::onAudioDeviceChangedDuringAudioSelection
Definition at line 99 of file AudioSelectComponent.h.
Referenced by processAudioSelectionChanges().
The documentation for this class was generated from the following files:
Source/MemaProcessorEditor/AudioSelectComponent.h
Source/MemaProcessorEditor/AudioSelectComponent.cpp