Mema: Mema::FaderbankControlComponent Class Reference
Mema::FaderbankControlComponent Class Reference
Fader-bank remote control — presents input×output crosspoint sliders and mute buttons.
#include <FaderbankControlComponent.h>
Public Member Functions
FaderbankControlComponent ()
virtual ~FaderbankControlComponent ()
void paint (Graphics &) override
void resized () override
void lookAndFeelChanged () override
void resetCtrl () override
void setControlsSize (const ControlsSize &ctrlsSize) override
void setIOCount (const std::pair< int, int > &ioCount) override
void setInputMuteStates (const std::map< std::uint16_t, bool > &inputMuteStates) override
void setOutputMuteStates (const std::map< std::uint16_t, bool > &outputMuteStates) override
void setCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &crosspointStates) override
void setCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > &crosspointValues) override
Public Member Functions inherited from Mema::MemaClientControlComponentBase
MemaClientControlComponentBase ()
virtual ~MemaClientControlComponentBase ()
const ControlsSize & getControlsSize ()
const std::pair< int, int > & getIOCount ()
const std::map< std::uint16_t, bool > & getInputMuteStates ()
const std::map< std::uint16_t, bool > & getOutputMuteStates ()
const std::map< std::uint16_t, std::map< std::uint16_t, bool > > & getCrosspointStates ()
const std::map< std::uint16_t, std::map< std::uint16_t, float > > & getCrosspointValues ()
virtual void addCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &crosspointStates)
virtual void addCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > &crosspointValues)
const juce::String getClientControlParametersAsString ()
const juce::String getIOCountParametersAsString ()
const juce::String getInputMuteParametersAsString ()
const juce::String getOutputMuteParametersAsString ()
const juce::String getCrosspointParametersAsString ()
Protected Member Functions
void selectIOChannel (const ControlDirection &direction, int channel)
void rebuildControls (bool force=false)
void rebuildInputControls (bool force=false)
void rebuildOutputControls (bool force=false)
void rebuildCrosspointControls (bool force=false)
void updateCrosspointFaderValues ()
Additional Inherited Members
Public Types inherited from Mema::MemaClientControlComponentBase
enum ControlDirection {
None = 0 ,
Input ,
Output
}
Direction of a control strip within the panel layout.
enum ControlsSize {
S = 35 ,
M = 50 ,
L = 65
}
Size category for rendered control elements.
Public Attributes inherited from Mema::MemaClientControlComponentBase
std::function< void(const std::map< std::uint16_t, bool > &)> onInputMutesChanged
std::function< void(const std::map< std::uint16_t, bool > &)> onOutputMutesChanged
std::function< void(const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &)> onCrosspointStatesChanged
std::function< void(const std::map< std::uint16_t, std::map< std::uint16_t, float > > &)> onCrosspointValuesChanged
Static Public Attributes inherited from Mema::MemaClientControlComponentBase
static constexpr int s_gap = 3
static constexpr int s_scrollbarsize = 8
Protected Attributes inherited from Mema::MemaClientControlComponentBase
ControlsSize m_controlsSize = ControlsSize::S
Detailed Description
Fader-bank remote control — presents input×output crosspoint sliders and mute buttons.
Part of the Mema.Re client. Implements MemaClientControlComponentBase to receive state snapshots from MemaProcessor and send updated ControlParametersMessage payloads back.
Definition at line 44 of file FaderbankControlComponent.h.
Constructor & Destructor Documentation
FaderbankControlComponent()
Mema::FaderbankControlComponent::FaderbankControlComponent ()
Definition at line 30 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::s_gap.
~FaderbankControlComponent()
Mema::FaderbankControlComponent::~FaderbankControlComponent () virtual
Definition at line 56 of file FaderbankControlComponent.cpp.
Member Function Documentation
lookAndFeelChanged()
void Mema::FaderbankControlComponent::lookAndFeelChanged () override
Definition at line 158 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::getIOCount(), Mema::MemaClientControlComponentBase::Input, and Mema::MemaClientControlComponentBase::Output.
paint()
void Mema::FaderbankControlComponent::paint (Graphics &) override virtual
Implements Mema::MemaClientControlComponentBase.
Definition at line 60 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::m_controlsSize, Mema::MemaClientControlComponentBase::s_gap, and Mema::MemaClientControlComponentBase::s_scrollbarsize.
rebuildControls()
void Mema::FaderbankControlComponent::rebuildControls (bool force = false) protected
Definition at line 203 of file FaderbankControlComponent.cpp.
References rebuildCrosspointControls(), rebuildInputControls(), rebuildOutputControls(), and resized().
Referenced by selectIOChannel(), setControlsSize(), and setIOCount().
rebuildCrosspointControls()
void Mema::FaderbankControlComponent::rebuildCrosspointControls (bool force = false) protected
Definition at line 336 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::addCrosspointStates(), Mema::MemaClientControlComponentBase::addCrosspointValues(), Mema::MemaClientControlComponentBase::getCrosspointStates(), Mema::MemaClientControlComponentBase::getCrosspointValues(), Mema::ProcessorDataAnalyzer::getGlobalMindB(), Mema::MemaClientControlComponentBase::getIOCount(), Mema::MemaClientControlComponentBase::Input, Mema::MemaClientControlComponentBase::m_controlsSize, Mema::MemaClientControlComponentBase::None, Mema::MemaClientControlComponentBase::onCrosspointStatesChanged, Mema::MemaClientControlComponentBase::onCrosspointValuesChanged, and Mema::MemaClientControlComponentBase::Output.
Referenced by rebuildControls().
rebuildInputControls()
void Mema::FaderbankControlComponent::rebuildInputControls (bool force = false) protected
Definition at line 211 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::getInputMuteStates(), Mema::MemaClientControlComponentBase::getIOCount(), Mema::MemaClientControlComponentBase::Input, Mema::MemaClientControlComponentBase::m_controlsSize, Mema::MemaClientControlComponentBase::None, Mema::MemaClientControlComponentBase::onInputMutesChanged, selectIOChannel(), and Mema::MemaClientControlComponentBase::setInputMuteStates().
Referenced by rebuildControls().
rebuildOutputControls()
void Mema::FaderbankControlComponent::rebuildOutputControls (bool force = false) protected
Definition at line 275 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::getIOCount(), Mema::MemaClientControlComponentBase::getOutputMuteStates(), Mema::MemaClientControlComponentBase::m_controlsSize, Mema::MemaClientControlComponentBase::None, Mema::MemaClientControlComponentBase::onOutputMutesChanged, Mema::MemaClientControlComponentBase::Output, selectIOChannel(), and Mema::MemaClientControlComponentBase::setOutputMuteStates().
Referenced by rebuildControls().
resetCtrl()
void Mema::FaderbankControlComponent::resetCtrl () override virtual
Implements Mema::MemaClientControlComponentBase.
Definition at line 185 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::None, selectIOChannel(), setCrosspointStates(), setCrosspointValues(), setInputMuteStates(), setIOCount(), and setOutputMuteStates().
resized()
void Mema::FaderbankControlComponent::resized () override virtual
Implements Mema::MemaClientControlComponentBase.
Definition at line 80 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::Input, Mema::MemaClientControlComponentBase::m_controlsSize, Mema::MemaClientControlComponentBase::None, Mema::MemaClientControlComponentBase::Output, Mema::MemaClientControlComponentBase::s_gap, and Mema::MemaClientControlComponentBase::s_scrollbarsize.
Referenced by rebuildControls().
selectIOChannel()
void Mema::FaderbankControlComponent::selectIOChannel (const ControlDirection & direction, int channel) protected
Definition at line 586 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::getIOCount(), Mema::MemaClientControlComponentBase::Input, Mema::MemaClientControlComponentBase::None, Mema::MemaClientControlComponentBase::Output, and rebuildControls().
Referenced by rebuildInputControls(), rebuildOutputControls(), resetCtrl(), setControlsSize(), and setIOCount().
setControlsSize()
void Mema::FaderbankControlComponent::setControlsSize (const ControlsSize & ctrlsSize) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 177 of file FaderbankControlComponent.cpp.
References rebuildControls(), selectIOChannel(), and Mema::MemaClientControlComponentBase::setControlsSize().
setCrosspointStates()
void Mema::FaderbankControlComponent::setCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > & crosspointStates) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 572 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::setCrosspointStates(), and updateCrosspointFaderValues().
Referenced by resetCtrl().
setCrosspointValues()
void Mema::FaderbankControlComponent::setCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > & crosspointValues) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 579 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::setCrosspointValues(), and updateCrosspointFaderValues().
Referenced by resetCtrl().
setInputMuteStates()
void Mema::FaderbankControlComponent::setInputMuteStates (const std::map< std::uint16_t, bool > & inputMuteStates) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 544 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::setInputMuteStates().
Referenced by resetCtrl().
setIOCount()
void Mema::FaderbankControlComponent::setIOCount (const std::pair< int, int > & ioCount) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 195 of file FaderbankControlComponent.cpp.
References rebuildControls(), selectIOChannel(), and Mema::MemaClientControlComponentBase::setIOCount().
Referenced by resetCtrl().
setOutputMuteStates()
void Mema::FaderbankControlComponent::setOutputMuteStates (const std::map< std::uint16_t, bool > & outputMuteStates) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 558 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::setOutputMuteStates().
Referenced by resetCtrl().
updateCrosspointFaderValues()
void Mema::FaderbankControlComponent::updateCrosspointFaderValues () protected
Definition at line 618 of file FaderbankControlComponent.cpp.
References Mema::MemaClientControlComponentBase::getCrosspointStates(), Mema::MemaClientControlComponentBase::getCrosspointValues(), Mema::MemaClientControlComponentBase::getIOCount(), Mema::MemaClientControlComponentBase::Input, Mema::MemaClientControlComponentBase::None, and Mema::MemaClientControlComponentBase::Output.
Referenced by setCrosspointStates(), and setCrosspointValues().
The documentation for this class was generated from the following files:
Source/MemaClientCommon/FaderbankControlComponent.h
Source/MemaClientCommon/FaderbankControlComponent.cpp