Mema: Mema::MemaClientControlComponentBase Class Reference
Mema::MemaClientControlComponentBase Class Reference abstract
Abstract base for all Mema.Re client control panels.
#include <MemaClientControlComponentBase.h>
Public Types
enum ControlDirection {
None = 0 ,
Input ,
Output
}
Direction of a control strip within the panel layout.
enum ControlsSize {
S = 35 ,
M = 50 ,
L = 65
}
Size category for rendered control elements.
Public Member Functions
MemaClientControlComponentBase ()
virtual ~MemaClientControlComponentBase ()
virtual void paint (Graphics &)=0
virtual void resized ()=0
virtual void resetCtrl ()=0
virtual void setControlsSize (const ControlsSize &ctrlsSize)
const ControlsSize & getControlsSize ()
virtual void setIOCount (const std::pair< int, int > &ioCount)
const std::pair< int, int > & getIOCount ()
virtual void setInputMuteStates (const std::map< std::uint16_t, bool > &inputMuteStates)
const std::map< std::uint16_t, bool > & getInputMuteStates ()
virtual void setOutputMuteStates (const std::map< std::uint16_t, bool > &outputMuteStates)
const std::map< std::uint16_t, bool > & getOutputMuteStates ()
virtual void setCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &crosspointStates)
const std::map< std::uint16_t, std::map< std::uint16_t, bool > > & getCrosspointStates ()
virtual void setCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > &crosspointValues)
const std::map< std::uint16_t, std::map< std::uint16_t, float > > & getCrosspointValues ()
virtual void addCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &crosspointStates)
virtual void addCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > &crosspointValues)
const juce::String getClientControlParametersAsString ()
const juce::String getIOCountParametersAsString ()
const juce::String getInputMuteParametersAsString ()
const juce::String getOutputMuteParametersAsString ()
const juce::String getCrosspointParametersAsString ()
Public Attributes
std::function< void(const std::map< std::uint16_t, bool > &)> onInputMutesChanged
std::function< void(const std::map< std::uint16_t, bool > &)> onOutputMutesChanged
std::function< void(const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &)> onCrosspointStatesChanged
std::function< void(const std::map< std::uint16_t, std::map< std::uint16_t, float > > &)> onCrosspointValuesChanged
Static Public Attributes
static constexpr int s_gap = 3
static constexpr int s_scrollbarsize = 8
Protected Attributes
ControlsSize m_controlsSize = ControlsSize::S
Detailed Description
Abstract base for all Mema.Re client control panels.
Defines the common interface for receiving Mema server state (IO counts, mute states, crosspoint values) and propagating user interactions back to the network layer.
Definition at line 34 of file MemaClientControlComponentBase.h.
Member Enumeration Documentation
ControlDirection
enum Mema::MemaClientControlComponentBase::ControlDirection
Direction of a control strip within the panel layout.
Enumerator
None
No directional context.
Input
Strip controls input channels.
Output
Strip controls output channels.
Definition at line 38 of file MemaClientControlComponentBase.h.
ControlsSize
enum Mema::MemaClientControlComponentBase::ControlsSize
Size category for rendered control elements.
Enumerator
S
Small — suited for desktop with many channels.
M
Medium.
L
Large — suited for touch screens.
Definition at line 45 of file MemaClientControlComponentBase.h.
Constructor & Destructor Documentation
MemaClientControlComponentBase()
Mema::MemaClientControlComponentBase::MemaClientControlComponentBase ()
Definition at line 28 of file MemaClientControlComponentBase.cpp.
~MemaClientControlComponentBase()
Mema::MemaClientControlComponentBase::~MemaClientControlComponentBase () virtual
Definition at line 33 of file MemaClientControlComponentBase.cpp.
Member Function Documentation
addCrosspointStates()
void Mema::MemaClientControlComponentBase::addCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > & crosspointStates) virtual
Definition at line 117 of file MemaClientControlComponentBase.cpp.
References getCrosspointStates(), and setCrosspointStates().
Referenced by Mema::PanningControlComponent::PanningControlComponent(), Mema::PanningControlComponent::processOutputDistances(), and Mema::FaderbankControlComponent::rebuildCrosspointControls().
addCrosspointValues()
void Mema::MemaClientControlComponentBase::addCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > & crosspointValues) virtual
Definition at line 134 of file MemaClientControlComponentBase.cpp.
References getCrosspointValues(), and setCrosspointValues().
Referenced by Mema::PanningControlComponent::PanningControlComponent(), Mema::PanningControlComponent::processOutputDistances(), and Mema::FaderbankControlComponent::rebuildCrosspointControls().
getClientControlParametersAsString()
const juce::String Mema::MemaClientControlComponentBase::getClientControlParametersAsString ()
Definition at line 151 of file MemaClientControlComponentBase.cpp.
References getCrosspointParametersAsString(), getInputMuteParametersAsString(), getIOCountParametersAsString(), and getOutputMuteParametersAsString().
getControlsSize()
const MemaClientControlComponentBase::ControlsSize & Mema::MemaClientControlComponentBase::getControlsSize ()
Definition at line 42 of file MemaClientControlComponentBase.cpp.
References m_controlsSize.
Referenced by Mema::PluginControlComponent::rebuildLayout().
getCrosspointParametersAsString()
const juce::String Mema::MemaClientControlComponentBase::getCrosspointParametersAsString ()
Definition at line 183 of file MemaClientControlComponentBase.cpp.
References getCrosspointStates(), and getCrosspointValues().
Referenced by getClientControlParametersAsString().
getCrosspointStates()
const std::map< std::uint16_t, std::map< std::uint16_t, bool > > & Mema::MemaClientControlComponentBase::getCrosspointStates ()
Definition at line 82 of file MemaClientControlComponentBase.cpp.
Referenced by addCrosspointStates(), getCrosspointParametersAsString(), Mema::PanningControlComponent::PanningControlComponent(), Mema::FaderbankControlComponent::rebuildCrosspointControls(), and Mema::FaderbankControlComponent::updateCrosspointFaderValues().
getCrosspointValues()
const std::map< std::uint16_t, std::map< std::uint16_t, float > > & Mema::MemaClientControlComponentBase::getCrosspointValues ()
Definition at line 102 of file MemaClientControlComponentBase.cpp.
Referenced by addCrosspointValues(), getCrosspointParametersAsString(), Mema::PanningControlComponent::PanningControlComponent(), Mema::FaderbankControlComponent::rebuildCrosspointControls(), and Mema::FaderbankControlComponent::updateCrosspointFaderValues().
getInputMuteParametersAsString()
const juce::String Mema::MemaClientControlComponentBase::getInputMuteParametersAsString ()
Definition at line 167 of file MemaClientControlComponentBase.cpp.
References getInputMuteStates().
Referenced by getClientControlParametersAsString().
getInputMuteStates()
const std::map< std::uint16_t, bool > & Mema::MemaClientControlComponentBase::getInputMuteStates ()
Definition at line 62 of file MemaClientControlComponentBase.cpp.
Referenced by getInputMuteParametersAsString(), Mema::FaderbankControlComponent::rebuildInputControls(), and Mema::PanningControlComponent::rebuildInputControls().
getIOCount()
const std::pair< int, int > & Mema::MemaClientControlComponentBase::getIOCount ()
Definition at line 52 of file MemaClientControlComponentBase.cpp.
Referenced by getIOCountParametersAsString(), Mema::FaderbankControlComponent::lookAndFeelChanged(), Mema::PanningControlComponent::lookAndFeelChanged(), Mema::FaderbankControlComponent::rebuildCrosspointControls(), Mema::FaderbankControlComponent::rebuildInputControls(), Mema::PanningControlComponent::rebuildInputControls(), Mema::FaderbankControlComponent::rebuildOutputControls(), Mema::PanningControlComponent::selectInputChannel(), Mema::FaderbankControlComponent::selectIOChannel(), and Mema::FaderbankControlComponent::updateCrosspointFaderValues().
getIOCountParametersAsString()
const juce::String Mema::MemaClientControlComponentBase::getIOCountParametersAsString ()
Definition at line 160 of file MemaClientControlComponentBase.cpp.
References getIOCount().
Referenced by getClientControlParametersAsString().
getOutputMuteParametersAsString()
const juce::String Mema::MemaClientControlComponentBase::getOutputMuteParametersAsString ()
Definition at line 175 of file MemaClientControlComponentBase.cpp.
References getOutputMuteStates().
Referenced by getClientControlParametersAsString().
getOutputMuteStates()
const std::map< std::uint16_t, bool > & Mema::MemaClientControlComponentBase::getOutputMuteStates ()
Definition at line 72 of file MemaClientControlComponentBase.cpp.
Referenced by getOutputMuteParametersAsString(), and Mema::FaderbankControlComponent::rebuildOutputControls().
paint()
virtual void Mema::MemaClientControlComponentBase::paint (Graphics &) pure virtual
Implemented in Mema::FaderbankControlComponent, Mema::PanningControlComponent, Mema::PluginControlComponent, and Mema::PluginControlComponent.
resetCtrl()
virtual void Mema::MemaClientControlComponentBase::resetCtrl () pure virtual
Implemented in Mema::FaderbankControlComponent, Mema::PanningControlComponent, and Mema::PluginControlComponent.
resized()
virtual void Mema::MemaClientControlComponentBase::resized () pure virtual
Implemented in Mema::FaderbankControlComponent, Mema::PanningControlComponent, Mema::PluginControlComponent, and Mema::PluginControlComponent.
setControlsSize()
void Mema::MemaClientControlComponentBase::setControlsSize (const ControlsSize & ctrlsSize) virtual
Reimplemented in Mema::FaderbankControlComponent, Mema::PanningControlComponent, and Mema::PluginControlComponent.
Definition at line 37 of file MemaClientControlComponentBase.cpp.
References m_controlsSize.
Referenced by Mema::FaderbankControlComponent::setControlsSize(), Mema::PanningControlComponent::setControlsSize(), and Mema::PluginControlComponent::setControlsSize().
setCrosspointStates()
void Mema::MemaClientControlComponentBase::setCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > & crosspointStates) virtual
Reimplemented in Mema::FaderbankControlComponent, and Mema::PanningControlComponent.
Definition at line 77 of file MemaClientControlComponentBase.cpp.
Referenced by addCrosspointStates(), Mema::FaderbankControlComponent::setCrosspointStates(), and Mema::PanningControlComponent::setCrosspointStates().
setCrosspointValues()
void Mema::MemaClientControlComponentBase::setCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > & crosspointValues) virtual
Reimplemented in Mema::FaderbankControlComponent, and Mema::PanningControlComponent.
Definition at line 87 of file MemaClientControlComponentBase.cpp.
Referenced by addCrosspointValues(), Mema::FaderbankControlComponent::setCrosspointValues(), and Mema::PanningControlComponent::setCrosspointValues().
setInputMuteStates()
void Mema::MemaClientControlComponentBase::setInputMuteStates (const std::map< std::uint16_t, bool > & inputMuteStates) virtual
Reimplemented in Mema::FaderbankControlComponent, and Mema::PanningControlComponent.
Definition at line 57 of file MemaClientControlComponentBase.cpp.
Referenced by Mema::FaderbankControlComponent::rebuildInputControls(), Mema::PanningControlComponent::rebuildInputControls(), Mema::FaderbankControlComponent::setInputMuteStates(), and Mema::PanningControlComponent::setInputMuteStates().
setIOCount()
void Mema::MemaClientControlComponentBase::setIOCount (const std::pair< int, int > & ioCount) virtual
Reimplemented in Mema::FaderbankControlComponent, and Mema::PanningControlComponent.
Definition at line 47 of file MemaClientControlComponentBase.cpp.
Referenced by Mema::PluginControlComponent::resetCtrl(), Mema::FaderbankControlComponent::setIOCount(), and Mema::PanningControlComponent::setIOCount().
setOutputMuteStates()
void Mema::MemaClientControlComponentBase::setOutputMuteStates (const std::map< std::uint16_t, bool > & outputMuteStates) virtual
Reimplemented in Mema::FaderbankControlComponent.
Definition at line 67 of file MemaClientControlComponentBase.cpp.
Referenced by Mema::FaderbankControlComponent::rebuildOutputControls(), and Mema::FaderbankControlComponent::setOutputMuteStates().
Member Data Documentation
m_controlsSize
ControlsSize Mema::MemaClientControlComponentBase::m_controlsSize = ControlsSize::S protected
Definition at line 103 of file MemaClientControlComponentBase.h.
Referenced by getControlsSize(), Mema::FaderbankControlComponent::paint(), Mema::PanningControlComponent::paint(), Mema::FaderbankControlComponent::rebuildCrosspointControls(), Mema::FaderbankControlComponent::rebuildInputControls(), Mema::PanningControlComponent::rebuildInputControls(), Mema::FaderbankControlComponent::rebuildOutputControls(), Mema::FaderbankControlComponent::resized(), Mema::PanningControlComponent::resized(), and setControlsSize().
onCrosspointStatesChanged
std::function<void(const std::map<std::uint16_t, std::map<std::uint16_t, bool>>&)> Mema::MemaClientControlComponentBase::onCrosspointStatesChanged
Definition at line 91 of file MemaClientControlComponentBase.h.
Referenced by Mema::PanningControlComponent::PanningControlComponent(), Mema::PanningControlComponent::processOutputDistances(), and Mema::FaderbankControlComponent::rebuildCrosspointControls().
onCrosspointValuesChanged
std::function<void(const std::map<std::uint16_t, std::map<std::uint16_t, float>>&)> Mema::MemaClientControlComponentBase::onCrosspointValuesChanged
Definition at line 92 of file MemaClientControlComponentBase.h.
Referenced by Mema::PanningControlComponent::PanningControlComponent(), Mema::PanningControlComponent::processOutputDistances(), and Mema::FaderbankControlComponent::rebuildCrosspointControls().
onInputMutesChanged
std::function<void(const std::map<std::uint16_t, bool>&)> Mema::MemaClientControlComponentBase::onInputMutesChanged
Definition at line 89 of file MemaClientControlComponentBase.h.
Referenced by Mema::FaderbankControlComponent::rebuildInputControls(), and Mema::PanningControlComponent::rebuildInputControls().
onOutputMutesChanged
std::function<void(const std::map<std::uint16_t, bool>&)> Mema::MemaClientControlComponentBase::onOutputMutesChanged
Definition at line 90 of file MemaClientControlComponentBase.h.
Referenced by Mema::FaderbankControlComponent::rebuildOutputControls().
s_gap
constexpr int Mema::MemaClientControlComponentBase::s_gap = 3 static constexpr
Definition at line 52 of file MemaClientControlComponentBase.h.
Referenced by Mema::FaderbankControlComponent::FaderbankControlComponent(), Mema::FaderbankControlComponent::paint(), Mema::PanningControlComponent::paint(), Mema::PanningControlComponent::PanningControlComponent(), Mema::FaderbankControlComponent::resized(), and Mema::PanningControlComponent::resized().
s_scrollbarsize
constexpr int Mema::MemaClientControlComponentBase::s_scrollbarsize = 8 static constexpr
Definition at line 53 of file MemaClientControlComponentBase.h.
Referenced by Mema::FaderbankControlComponent::paint(), Mema::FaderbankControlComponent::resized(), and Mema::PanningControlComponent::resized().
The documentation for this class was generated from the following files:
Source/MemaClientCommon/MemaClientControlComponentBase.h
Source/MemaClientCommon/MemaClientControlComponentBase.cpp