Mema: Mema::ProcessorAudioSignalData Class Reference
Mema::ProcessorAudioSignalData Class Reference
#include <ProcessorAudioSignalData.h>
Public Member Functions
ProcessorAudioSignalData ()
~ProcessorAudioSignalData ()
void SetChannelCount (unsigned long count) override
Sets the number of channels in the audio buffer.
unsigned long GetChannelCount () override
Returns the number of channels in the audio buffer.
void SetSampleRate (unsigned long rate)
Sets the sample rate associated with this buffer.
unsigned long GetSampleRate ()
Returns the sample rate associated with this buffer.
Public Member Functions inherited from Mema::AbstractProcessorData
AbstractProcessorData ()
virtual ~AbstractProcessorData ()
Type GetDataType ()
Returns the concrete type of this data object.
Additional Inherited Members
Public Types inherited from Mema::AbstractProcessorData
enum Type {
Invalid ,
AudioSignal ,
Level ,
Spectrum
}
Identifies the concrete payload type carried by this data object.
Protected Attributes inherited from Mema::AbstractProcessorData
Type m_type
Detailed Description
buffer data object carrying raw PCM samples plus sample-rate metadata.
Definition at line 28 of file ProcessorAudioSignalData.h.
Constructor & Destructor Documentation
ProcessorAudioSignalData()
Mema::ProcessorAudioSignalData::ProcessorAudioSignalData ()
Definition at line 24 of file ProcessorAudioSignalData.cpp.
References Mema::AbstractProcessorData::AudioSignal, and Mema::AbstractProcessorData::m_type.
~ProcessorAudioSignalData()
Mema::ProcessorAudioSignalData::~ProcessorAudioSignalData ()
Definition at line 31 of file ProcessorAudioSignalData.cpp.
Member Function Documentation
GetChannelCount()
unsigned long Mema::ProcessorAudioSignalData::GetChannelCount () override virtual
Returns the number of channels in the audio buffer.
Implements Mema::AbstractProcessorData.
Definition at line 41 of file ProcessorAudioSignalData.cpp.
Referenced by Mema::WaveformAudioComponent::processingDataChanged().
GetSampleRate()
unsigned long Mema::ProcessorAudioSignalData::GetSampleRate ()
Returns the sample rate associated with this buffer.
Definition at line 51 of file ProcessorAudioSignalData.cpp.
Referenced by Mema::ProcessorDataAnalyzer::analyzeData().
SetChannelCount()
void Mema::ProcessorAudioSignalData::SetChannelCount (unsigned long count) override virtual
Sets the number of channels in the audio buffer.
Implements Mema::AbstractProcessorData.
Definition at line 36 of file ProcessorAudioSignalData.cpp.
SetSampleRate()
void Mema::ProcessorAudioSignalData::SetSampleRate (unsigned long rate)
Sets the sample rate associated with this buffer.
Definition at line 46 of file ProcessorAudioSignalData.cpp.
Referenced by Mema::ProcessorDataAnalyzer::analyzeData().
The documentation for this class was generated from the following files:
Source/MemaProcessor/ProcessorAudioSignalData.h
Source/MemaProcessor/ProcessorAudioSignalData.cpp