Mema: Mema::AbstractAudioVisualizer Class Reference
Mema::AbstractAudioVisualizer Class Reference
Base class for all audio-data visualisation components in the Mema processor editor.
#include <AbstractAudioVisualizer.h>
Public Member Functions
AbstractAudioVisualizer ()
virtual ~AbstractAudioVisualizer ()
void notifyChanges ()
Marks that new data is available and triggers a repaint on the next timer tick.
virtual void processChanges ()
Called on the message thread to update cached data before repainting.
void paint (Graphics &) override
Paints the visualiser background.
void resized () override
Lays out child components.
void mouseDown (const MouseEvent &event) override
Handles mouse-down events (e.g. right-click context menu).
void setRefreshFrequency (int frequency)
Sets the display refresh rate in Hz.
void timerCallback () override
Timer callback that calls processChanges() and triggers a repaint if data changed.
Public Member Functions inherited from Mema::ProcessorDataAnalyzer::Listener
virtual ~Listener ()
virtual void processingDataChanged (AbstractProcessorData *data)=0
Protected Member Functions
void setUsesValuesInDB (bool useValuesInDB)
bool getUsesValuesInDB ()
Detailed Description
Base class for all audio-data visualisation components in the Mema processor editor.
Implements juce::Timer and ProcessorDataAnalyzer::Listener to receive level/spectrum notifications and trigger repaints at a configurable refresh rate.
Definition at line 34 of file AbstractAudioVisualizer.h.
Constructor & Destructor Documentation
AbstractAudioVisualizer()
Mema::AbstractAudioVisualizer::AbstractAudioVisualizer ()
Definition at line 28 of file AbstractAudioVisualizer.cpp.
References setRefreshFrequency().
~AbstractAudioVisualizer()
Mema::AbstractAudioVisualizer::~AbstractAudioVisualizer () virtual
Definition at line 36 of file AbstractAudioVisualizer.cpp.
Member Function Documentation
getUsesValuesInDB()
bool Mema::AbstractAudioVisualizer::getUsesValuesInDB () protected
Definition at line 70 of file AbstractAudioVisualizer.cpp.
Referenced by Mema::TwoDFieldOutputComponent::paint(), and Mema::MeterbridgeComponent::paint().
mouseDown()
void Mema::AbstractAudioVisualizer::mouseDown (const MouseEvent & event) override
Handles mouse-down events (e.g. right-click context menu).
Definition at line 50 of file AbstractAudioVisualizer.cpp.
notifyChanges()
void Mema::AbstractAudioVisualizer::notifyChanges ()
Marks that new data is available and triggers a repaint on the next timer tick.
Definition at line 129 of file AbstractAudioVisualizer.cpp.
Referenced by Mema::SpectrumAudioComponent::processingDataChanged(), Mema::TwoDFieldOutputComponent::processingDataChanged(), Mema::WaveformAudioComponent::processingDataChanged(), Mema::InputControlComponent::processingDataChanged(), Mema::MeterbridgeComponent::processingDataChanged(), and Mema::OutputControlComponent::processingDataChanged().
paint()
void Mema::AbstractAudioVisualizer::paint (Graphics & g) override
Paints the visualiser background.
Definition at line 40 of file AbstractAudioVisualizer.cpp.
Referenced by Mema::TwoDFieldOutputComponent::paint(), Mema::InputControlComponent::paint(), Mema::OutputControlComponent::paint(), Mema::SpectrumAudioComponent::paint(), and Mema::WaveformAudioComponent::paint().
processChanges()
void Mema::AbstractAudioVisualizer::processChanges () virtual
Called on the message thread to update cached data before repainting.
Reimplemented in Mema::InputControlComponent, and Mema::OutputControlComponent.
Definition at line 134 of file AbstractAudioVisualizer.cpp.
Referenced by Mema::InputControlComponent::processChanges(), Mema::OutputControlComponent::processChanges(), and timerCallback().
resized()
void Mema::AbstractAudioVisualizer::resized () override
Lays out child components.
Definition at line 45 of file AbstractAudioVisualizer.cpp.
Referenced by Mema::SpectrumAudioComponent::resized(), Mema::TwoDFieldOutputComponent::resized(), Mema::WaveformAudioComponent::resized(), Mema::InputControlComponent::resized(), and Mema::OutputControlComponent::resized().
setRefreshFrequency()
void Mema::AbstractAudioVisualizer::setRefreshFrequency (int frequency)
Sets the display refresh rate in Hz.
Definition at line 55 of file AbstractAudioVisualizer.cpp.
Referenced by AbstractAudioVisualizer(), Mema::MeterbridgeComponent::MeterbridgeComponent(), and Mema::SpectrumAudioComponent::SpectrumAudioComponent().
setUsesValuesInDB()
void Mema::AbstractAudioVisualizer::setUsesValuesInDB (bool useValuesInDB) protected
Definition at line 65 of file AbstractAudioVisualizer.cpp.
Referenced by Mema::InputControlComponent::InputControlComponent(), Mema::MeterbridgeComponent::MeterbridgeComponent(), Mema::OutputControlComponent::OutputControlComponent(), and Mema::TwoDFieldOutputComponent::TwoDFieldOutputComponent().
timerCallback()
void Mema::AbstractAudioVisualizer::timerCallback () override
Timer callback that calls processChanges() and triggers a repaint if data changed.
Definition at line 60 of file AbstractAudioVisualizer.cpp.
References processChanges().
The documentation for this class was generated from the following files:
Source/MemaProcessorEditor/AbstractAudioVisualizer.h
Source/MemaProcessorEditor/AbstractAudioVisualizer.cpp