Mema: Mema::CrosspointsControlComponent Class Reference
Mema::CrosspointsControlComponent Class Reference
#include <CrosspointsControlComponent.h>
Public Member Functions
CrosspointsControlComponent ()
~CrosspointsControlComponent ()
void paint (Graphics &) override
void resized () override
void setCrosspointEnabledValue (std::uint16_t input, std::uint16_t output, bool enabledState, int userId=-1) override
void setCrosspointFactorValue (std::uint16_t input, std::uint16_t output, float factor, int userId=-1) override
juce::Rectangle< int > getRequiredSize ()
void setIOCount (std::uint16_t inputCount, std::uint16_t outputCount) override
Public Member Functions inherited from Mema::MemaCrosspointCommander
MemaCrosspointCommander ()
virtual ~MemaCrosspointCommander () override
void setCrosspointEnabledChangeCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t, bool)> &callback)
void setCrosspointEnabledPollCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t)> &callback)
void setCrosspointFactorChangeCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t, float)> &callback)
void setCrosspointFactorPollCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t)> &callback)
Public Member Functions inherited from Mema::MemaChannelCommander
MemaChannelCommander ()
virtual ~MemaChannelCommander ()
Public Attributes
std::function< void()> onBoundsRequirementChange
Additional Inherited Members
Protected Member Functions inherited from Mema::MemaCrosspointCommander
void crosspointEnabledChange (std::uint16_t input, std::uint16_t output, bool enabledState, MemaCrosspointCommander *sender)
void crosspointEnabledPoll (std::uint16_t input, std::uint16_t output, MemaCrosspointCommander *sender)
void crosspointFactorChange (std::uint16_t input, std::uint16_t output, float factor, MemaCrosspointCommander *sender)
void crosspointFactorPoll (std::uint16_t input, std::uint16_t output, MemaCrosspointCommander *sender)
Detailed Description
grid component showing and controlling all input×output crosspoints.
Definition at line 167 of file CrosspointsControlComponent.h.
Constructor & Destructor Documentation
CrosspointsControlComponent()
Mema::CrosspointsControlComponent::CrosspointsControlComponent ()
Definition at line 26 of file CrosspointsControlComponent.cpp.
~CrosspointsControlComponent()
Mema::CrosspointsControlComponent::~CrosspointsControlComponent ()
Definition at line 33 of file CrosspointsControlComponent.cpp.
Member Function Documentation
getRequiredSize()
juce::Rectangle< int > Mema::CrosspointsControlComponent::getRequiredSize ()
Definition at line 139 of file CrosspointsControlComponent.cpp.
paint()
void Mema::CrosspointsControlComponent::paint (Graphics & g) override
Definition at line 42 of file CrosspointsControlComponent.cpp.
resized()
void Mema::CrosspointsControlComponent::resized () override
Definition at line 37 of file CrosspointsControlComponent.cpp.
Referenced by setIOCount().
setCrosspointEnabledValue()
void Mema::CrosspointsControlComponent::setCrosspointEnabledValue (std::uint16_t input, std::uint16_t output, bool enabledState, int userId = -1) override virtual
Implements Mema::MemaCrosspointCommander.
Definition at line 48 of file CrosspointsControlComponent.cpp.
setCrosspointFactorValue()
void Mema::CrosspointsControlComponent::setCrosspointFactorValue (std::uint16_t input, std::uint16_t output, float factor, int userId = -1) override virtual
Implements Mema::MemaCrosspointCommander.
Definition at line 57 of file CrosspointsControlComponent.cpp.
setIOCount()
void Mema::CrosspointsControlComponent::setIOCount (std::uint16_t inputCount, std::uint16_t outputCount) override virtual
Implements Mema::MemaCrosspointCommander.
Definition at line 66 of file CrosspointsControlComponent.cpp.
References Mema::MemaCrosspointCommander::crosspointEnabledChange(), Mema::MemaCrosspointCommander::crosspointFactorChange(), onBoundsRequirementChange, and resized().
Member Data Documentation
onBoundsRequirementChange
std::function<void()> Mema::CrosspointsControlComponent::onBoundsRequirementChange
Definition at line 183 of file CrosspointsControlComponent.h.
Referenced by setIOCount().
The documentation for this class was generated from the following files:
Source/MemaProcessorEditor/CrosspointsControlComponent.h
Source/MemaProcessorEditor/CrosspointsControlComponent.cpp