Mema: Mema::ProcessorLevelData Class Reference
Mema::ProcessorLevelData Class Reference
#include <ProcessorLevelData.h>
Classes
struct LevelVal
Per-channel level values in both linear and dB domains.
Public Member Functions
ProcessorLevelData ()
~ProcessorLevelData ()
void SetLevel (unsigned long channel, LevelVal level)
LevelVal GetLevel (unsigned long channel)
void SetChannelCount (unsigned long count) override
Sets the number of audio channels this data object covers.
unsigned long GetChannelCount () override
Returns the number of audio channels this data object covers.
Public Member Functions inherited from Mema::AbstractProcessorData
AbstractProcessorData ()
virtual ~AbstractProcessorData ()
Type GetDataType ()
Returns the concrete type of this data object.
Additional Inherited Members
Public Types inherited from Mema::AbstractProcessorData
enum Type {
Invalid ,
AudioSignal ,
Level ,
Spectrum
}
Identifies the concrete payload type carried by this data object.
Protected Attributes inherited from Mema::AbstractProcessorData
Type m_type
Detailed Description
data object carrying peak, RMS, and hold values for each channel.
Definition at line 27 of file ProcessorLevelData.h.
Constructor & Destructor Documentation
ProcessorLevelData()
Mema::ProcessorLevelData::ProcessorLevelData ()
Definition at line 24 of file ProcessorLevelData.cpp.
References Mema::AbstractProcessorData::Level, and Mema::AbstractProcessorData::m_type.
~ProcessorLevelData()
Mema::ProcessorLevelData::~ProcessorLevelData ()
Definition at line 29 of file ProcessorLevelData.cpp.
Member Function Documentation
GetChannelCount()
unsigned long Mema::ProcessorLevelData::GetChannelCount () override virtual
Returns the number of audio channels this data object covers.
Implements Mema::AbstractProcessorData.
Definition at line 59 of file ProcessorLevelData.cpp.
Referenced by SetChannelCount().
GetLevel()
ProcessorLevelData::LevelVal Mema::ProcessorLevelData::GetLevel (unsigned long channel)
Definition at line 39 of file ProcessorLevelData.cpp.
Referenced by Mema::ProcessorDataAnalyzer::analyzeData(), and Mema::MeterbridgeComponent::paint().
SetChannelCount()
void Mema::ProcessorLevelData::SetChannelCount (unsigned long count) override virtual
Sets the number of audio channels this data object covers.
Implements Mema::AbstractProcessorData.
Definition at line 47 of file ProcessorLevelData.cpp.
References GetChannelCount().
SetLevel()
void Mema::ProcessorLevelData::SetLevel (unsigned long channel, ProcessorLevelData::LevelVal level)
Definition at line 34 of file ProcessorLevelData.cpp.
Referenced by Mema::ProcessorDataAnalyzer::analyzeData().
The documentation for this class was generated from the following files:
Source/MemaProcessor/ProcessorLevelData.h
Source/MemaProcessor/ProcessorLevelData.cpp