Mema: Mema::AbstractProcessorData Class Reference
Mema::AbstractProcessorData Class Reference abstract
Base class for all data objects exchanged between the audio processor and its analyzers/visualisers.
#include <AbstractProcessorData.h>
Public Types
enum Type {
Invalid ,
AudioSignal ,
Level ,
Spectrum
}
Identifies the concrete payload type carried by this data object.
Public Member Functions
AbstractProcessorData ()
virtual ~AbstractProcessorData ()
Type GetDataType ()
Returns the concrete type of this data object.
virtual void SetChannelCount (unsigned long count)=0
Sets the number of audio channels this data object covers.
virtual unsigned long GetChannelCount ()=0
Returns the number of audio channels this data object covers.
Protected Attributes
Type m_type
Detailed Description
Base class for all data objects exchanged between the audio processor and its analyzers/visualisers.
Definition at line 29 of file AbstractProcessorData.h.
Member Enumeration Documentation
Type
enum Mema::AbstractProcessorData::Type
Identifies the concrete payload type carried by this data object.
Enumerator
Invalid
Uninitialised or unknown data.
AudioSignal
Raw audio buffer data.
Level
Peak/RMS/hold level metering data.
Spectrum
FFT frequency-spectrum data.
Definition at line 33 of file AbstractProcessorData.h.
Constructor & Destructor Documentation
AbstractProcessorData()
Mema::AbstractProcessorData::AbstractProcessorData ()
Definition at line 24 of file AbstractProcessorData.cpp.
References Invalid, and m_type.
~AbstractProcessorData()
Mema::AbstractProcessorData::~AbstractProcessorData () virtual
Definition at line 29 of file AbstractProcessorData.cpp.
Member Function Documentation
GetChannelCount()
virtual unsigned long Mema::AbstractProcessorData::GetChannelCount () pure virtual
Returns the number of audio channels this data object covers.
Implemented in Mema::ProcessorAudioSignalData, Mema::ProcessorLevelData, and Mema::ProcessorSpectrumData.
GetDataType()
AbstractProcessorData::Type Mema::AbstractProcessorData::GetDataType ()
Returns the concrete type of this data object.
Definition at line 34 of file AbstractProcessorData.cpp.
References m_type.
Referenced by Mema::SpectrumAudioComponent::processingDataChanged(), Mema::TwoDFieldOutputComponent::processingDataChanged(), Mema::WaveformAudioComponent::processingDataChanged(), Mema::InputControlComponent::processingDataChanged(), Mema::MeterbridgeComponent::processingDataChanged(), and Mema::OutputControlComponent::processingDataChanged().
SetChannelCount()
virtual void Mema::AbstractProcessorData::SetChannelCount (unsigned long count) pure virtual
Sets the number of audio channels this data object covers.
Implemented in Mema::ProcessorAudioSignalData, Mema::ProcessorLevelData, and Mema::ProcessorSpectrumData.
Member Data Documentation
m_type
Type Mema::AbstractProcessorData::m_type protected
Definition at line 53 of file AbstractProcessorData.h.
Referenced by AbstractProcessorData(), GetDataType(), Mema::ProcessorAudioSignalData::ProcessorAudioSignalData(), Mema::ProcessorLevelData::ProcessorLevelData(), and Mema::ProcessorSpectrumData::ProcessorSpectrumData().
The documentation for this class was generated from the following files:
Source/MemaProcessor/AbstractProcessorData.h
Source/MemaProcessor/AbstractProcessorData.cpp