Mema: Mema::OutputControlComponent Class Reference
Mema::OutputControlComponent Class Reference
Output-channel control strip — shows level meters and mute buttons for all output channels.
#include <OutputControlComponent.h>
Public Member Functions
OutputControlComponent ()
~OutputControlComponent ()
void paint (Graphics &) override
void resized () override
void processingDataChanged (AbstractProcessorData *data) override
virtual void processChanges () override
Called on the message thread to update cached data before repainting.
void setOutputMute (std::uint16_t channel, bool muteState, int userId=-1) override
void buttonClicked (juce::Button *) override
juce::Rectangle< int > getRequiredSize ()
void setChannelCount (std::uint16_t channelCount) override
Public Member Functions inherited from Mema::AbstractAudioVisualizer
AbstractAudioVisualizer ()
virtual ~AbstractAudioVisualizer ()
void notifyChanges ()
Marks that new data is available and triggers a repaint on the next timer tick.
void paint (Graphics &) override
Paints the visualiser background.
void resized () override
Lays out child components.
void mouseDown (const MouseEvent &event) override
Handles mouse-down events (e.g. right-click context menu).
void setRefreshFrequency (int frequency)
Sets the display refresh rate in Hz.
void timerCallback () override
Timer callback that calls processChanges() and triggers a repaint if data changed.
Public Member Functions inherited from Mema::ProcessorDataAnalyzer::Listener
virtual ~Listener ()
Public Member Functions inherited from Mema::MemaOutputCommander
MemaOutputCommander ()
virtual ~MemaOutputCommander () override
void setOutputMuteChangeCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t, bool)> &callback)
void setOutputLevelChangeCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t, float)> &callback)
void setOutputMutePollCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t)> &callback)
void setOutputLevelPollCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t)> &callback)
virtual void setOutputLevel (std::uint16_t channel, float levelValue, int userId=-1)
Public Member Functions inherited from Mema::MemaChannelCommander
MemaChannelCommander ()
virtual ~MemaChannelCommander ()
Public Attributes
std::function< void()> onBoundsRequirementChange
Additional Inherited Members
Protected Member Functions inherited from Mema::AbstractAudioVisualizer
void setUsesValuesInDB (bool useValuesInDB)
bool getUsesValuesInDB ()
Protected Member Functions inherited from Mema::MemaOutputCommander
void outputMuteChange (std::uint16_t channel, bool muteState, MemaOutputCommander *sender)
void outputLevelChange (std::uint16_t channel, float levelValue, MemaOutputCommander *sender)
void outputMutePoll (std::uint16_t channel, MemaOutputCommander *sender)
void outputLevelPoll (std::uint16_t channel, MemaOutputCommander *sender)
Detailed Description
Output-channel control strip — shows level meters and mute buttons for all output channels.
Inherits AbstractAudioVisualizer (receives output analyzer data) and MemaOutputCommander (sends mute commands back to MemaProcessor).
Definition at line 41 of file OutputControlComponent.h.
Constructor & Destructor Documentation
OutputControlComponent()
Mema::OutputControlComponent::OutputControlComponent ()
Definition at line 28 of file OutputControlComponent.cpp.
References Mema::AbstractAudioVisualizer::setUsesValuesInDB(), and Mema::MeterbridgeComponent::Vertical.
~OutputControlComponent()
Mema::OutputControlComponent::~OutputControlComponent ()
Definition at line 37 of file OutputControlComponent.cpp.
Member Function Documentation
buttonClicked()
void Mema::OutputControlComponent::buttonClicked (juce::Button * button) override
Definition at line 151 of file OutputControlComponent.cpp.
References Mema::MemaOutputCommander::outputMuteChange().
getRequiredSize()
juce::Rectangle< int > Mema::OutputControlComponent::getRequiredSize ()
Definition at line 158 of file OutputControlComponent.cpp.
paint()
void Mema::OutputControlComponent::paint (Graphics & g) override
Definition at line 63 of file OutputControlComponent.cpp.
References Mema::AbstractAudioVisualizer::paint().
processChanges()
void Mema::OutputControlComponent::processChanges () override virtual
Called on the message thread to update cached data before repainting.
Reimplemented from Mema::AbstractAudioVisualizer.
Definition at line 100 of file OutputControlComponent.cpp.
References Mema::AbstractAudioVisualizer::processChanges().
processingDataChanged()
void Mema::OutputControlComponent::processingDataChanged (AbstractProcessorData * data) override virtual
Implements Mema::ProcessorDataAnalyzer::Listener.
Definition at line 81 of file OutputControlComponent.cpp.
References Mema::AbstractProcessorData::AudioSignal, Mema::AbstractProcessorData::GetDataType(), Mema::AbstractProcessorData::Invalid, Mema::AbstractProcessorData::Level, Mema::AbstractAudioVisualizer::notifyChanges(), and Mema::AbstractProcessorData::Spectrum.
resized()
void Mema::OutputControlComponent::resized () override
Definition at line 42 of file OutputControlComponent.cpp.
References Mema::AbstractAudioVisualizer::resized().
Referenced by setChannelCount().
setChannelCount()
void Mema::OutputControlComponent::setChannelCount (std::uint16_t channelCount) override virtual
Implements Mema::MemaChannelCommander.
Definition at line 109 of file OutputControlComponent.cpp.
References onBoundsRequirementChange, and resized().
setOutputMute()
void Mema::OutputControlComponent::setOutputMute (std::uint16_t channel, bool muteState, int userId = -1) override virtual
Implements Mema::MemaOutputCommander.
Definition at line 72 of file OutputControlComponent.cpp.
Member Data Documentation
onBoundsRequirementChange
std::function<void()> Mema::OutputControlComponent::onBoundsRequirementChange
Definition at line 67 of file OutputControlComponent.h.
Referenced by setChannelCount().
The documentation for this class was generated from the following files:
Source/MemaProcessorEditor/OutputControlComponent.h
Source/MemaProcessorEditor/OutputControlComponent.cpp