Mema: MemaClientDiscoverComponent Class Reference
MemaClientDiscoverComponent Class Reference
#include <MemaClientDiscoverComponent.h>
Public Member Functions
MemaClientDiscoverComponent ()
~MemaClientDiscoverComponent () override
void paint (Graphics &) override
void resized () override
void lookAndFeelChanged () override
void setupServiceDiscovery (const juce::String &serviceTypeUIDBase, const juce::String &serviceTypeUID)
void resetServices ()
std::vector< JUCEAppBasics::SessionMasterAwareService > getAvailableServices ()
void setMasterServiceDescription (const juce::String &masterServiceDescription)
Public Attributes
std::function< void(const JUCEAppBasics::SessionMasterAwareService &)> onServiceSelected
Detailed Description
panel that listens for Mema multicast announcements and lists available instances.
Definition at line 31 of file MemaClientDiscoverComponent.h.
Constructor & Destructor Documentation
MemaClientDiscoverComponent()
MemaClientDiscoverComponent::MemaClientDiscoverComponent ()
Definition at line 27 of file MemaClientDiscoverComponent.cpp.
References onServiceSelected.
~MemaClientDiscoverComponent()
MemaClientDiscoverComponent::~MemaClientDiscoverComponent () override
Definition at line 49 of file MemaClientDiscoverComponent.cpp.
Member Function Documentation
getAvailableServices()
std::vector< JUCEAppBasics::SessionMasterAwareService > MemaClientDiscoverComponent::getAvailableServices ()
Definition at line 133 of file MemaClientDiscoverComponent.cpp.
lookAndFeelChanged()
void MemaClientDiscoverComponent::lookAndFeelChanged () override
Definition at line 89 of file MemaClientDiscoverComponent.cpp.
paint()
void MemaClientDiscoverComponent::paint (Graphics & g) override
Definition at line 53 of file MemaClientDiscoverComponent.cpp.
resetServices()
void MemaClientDiscoverComponent::resetServices ()
Definition at line 96 of file MemaClientDiscoverComponent.cpp.
References setMasterServiceDescription().
resized()
void MemaClientDiscoverComponent::resized () override
Definition at line 58 of file MemaClientDiscoverComponent.cpp.
setMasterServiceDescription()
void MemaClientDiscoverComponent::setMasterServiceDescription (const juce::String & masterServiceDescription)
Definition at line 141 of file MemaClientDiscoverComponent.cpp.
Referenced by resetServices().
setupServiceDiscovery()
void MemaClientDiscoverComponent::setupServiceDiscovery (const juce::String & serviceTypeUIDBase, const juce::String & serviceTypeUID)
Definition at line 101 of file MemaClientDiscoverComponent.cpp.
References Mema::ServiceData::getBroadcastPort(), Mema::ServiceData::getConnectionPort(), and setupServiceDiscovery().
Referenced by setupServiceDiscovery().
Member Data Documentation
onServiceSelected
std::function<void(const JUCEAppBasics::SessionMasterAwareService&)> MemaClientDiscoverComponent::onServiceSelected
Definition at line 50 of file MemaClientDiscoverComponent.h.
Referenced by MemaClientDiscoverComponent().
The documentation for this class was generated from the following files:
Source/MemaClientCommon/MemaClientDiscoverComponent.h
Source/MemaClientCommon/MemaClientDiscoverComponent.cpp