Mema: Mema::TwoDFieldOutputComponent Class Reference
Mema::TwoDFieldOutputComponent Class Reference
#include <TwoDFieldOutputComponent.h>
Public Member Functions
TwoDFieldOutputComponent ()
~TwoDFieldOutputComponent ()
void paint (Graphics &) override
void resized () override
void processingDataChanged (AbstractProcessorData *data) override
Public Member Functions inherited from Mema::AbstractAudioVisualizer
AbstractAudioVisualizer ()
virtual ~AbstractAudioVisualizer ()
void notifyChanges ()
Marks that new data is available and triggers a repaint on the next timer tick.
virtual void processChanges ()
Called on the message thread to update cached data before repainting.
void paint (Graphics &) override
Paints the visualiser background.
void resized () override
Lays out child components.
void mouseDown (const MouseEvent &event) override
Handles mouse-down events (e.g. right-click context menu).
void setRefreshFrequency (int frequency)
Sets the display refresh rate in Hz.
void timerCallback () override
Timer callback that calls processChanges() and triggers a repaint if data changed.
Public Member Functions inherited from Mema::ProcessorDataAnalyzer::Listener
virtual ~Listener ()
Additional Inherited Members
Protected Member Functions inherited from Mema::AbstractAudioVisualizer
void setUsesValuesInDB (bool useValuesInDB)
bool getUsesValuesInDB ()
Detailed Description
spatial output level display — paints circular level indicators at speaker positions for LRS up to 9.1.6 ATMOS layouts.
Definition at line 30 of file TwoDFieldOutputComponent.h.
Constructor & Destructor Documentation
TwoDFieldOutputComponent()
Mema::TwoDFieldOutputComponent::TwoDFieldOutputComponent ()
Definition at line 30 of file TwoDFieldOutputComponent.cpp.
References Mema::AbstractAudioVisualizer::setUsesValuesInDB().
~TwoDFieldOutputComponent()
Mema::TwoDFieldOutputComponent::~TwoDFieldOutputComponent ()
Definition at line 36 of file TwoDFieldOutputComponent.cpp.
Member Function Documentation
paint()
void Mema::TwoDFieldOutputComponent::paint (Graphics &) override
Definition at line 40 of file TwoDFieldOutputComponent.cpp.
References Mema::ProcessorDataAnalyzer::getGlobalMaxdB(), Mema::ProcessorDataAnalyzer::getGlobalMindB(), Mema::AbstractAudioVisualizer::getUsesValuesInDB(), and Mema::AbstractAudioVisualizer::paint().
processingDataChanged()
void Mema::TwoDFieldOutputComponent::processingDataChanged (AbstractProcessorData * data) override virtual
Implements Mema::ProcessorDataAnalyzer::Listener.
Definition at line 377 of file TwoDFieldOutputComponent.cpp.
References Mema::AbstractProcessorData::AudioSignal, Mema::AbstractProcessorData::GetDataType(), Mema::AbstractProcessorData::Invalid, Mema::AbstractProcessorData::Level, Mema::AbstractAudioVisualizer::notifyChanges(), and Mema::AbstractProcessorData::Spectrum.
resized()
void Mema::TwoDFieldOutputComponent::resized () override
Definition at line 305 of file TwoDFieldOutputComponent.cpp.
References Mema::AbstractAudioVisualizer::resized().
The documentation for this class was generated from the following files:
Source/MemaClientCommon/TwoDFieldOutputComponent.h
Source/MemaClientCommon/TwoDFieldOutputComponent.cpp