Mema: Mema::PanningControlComponent Class Reference
Mema::PanningControlComponent Class Reference
2-D spatial panning remote control for Mema.Re.
#include <PanningControlComponent.h>
Public Member Functions
PanningControlComponent ()
virtual ~PanningControlComponent ()
void paint (Graphics &) override
void resized () override
void lookAndFeelChanged () override
void resetCtrl () override
void setControlsSize (const ControlsSize &ctrlsSize) override
void setIOCount (const std::pair< int, int > &ioCount) override
void setInputMuteStates (const std::map< std::uint16_t, bool > &inputMuteStates) override
void setCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &crosspointStates) override
void setCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > &crosspointValues) override
void setChannelConfig (const juce::AudioChannelSet &channelConfiguration)
const juce::AudioChannelSet & getChannelConfig ()
void setExternalControlSettings (int ADMOSCPort, const juce::IPAddress &ADMOSCControllerIP, int ADMOSCControllerPort)
void handleExternalControlParameter (int objNum, std::uint16_t objType, void *sender=nullptr)
Public Member Functions inherited from Mema::MemaClientControlComponentBase
MemaClientControlComponentBase ()
virtual ~MemaClientControlComponentBase ()
const ControlsSize & getControlsSize ()
const std::pair< int, int > & getIOCount ()
const std::map< std::uint16_t, bool > & getInputMuteStates ()
virtual void setOutputMuteStates (const std::map< std::uint16_t, bool > &outputMuteStates)
const std::map< std::uint16_t, bool > & getOutputMuteStates ()
const std::map< std::uint16_t, std::map< std::uint16_t, bool > > & getCrosspointStates ()
const std::map< std::uint16_t, std::map< std::uint16_t, float > > & getCrosspointValues ()
virtual void addCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &crosspointStates)
virtual void addCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > &crosspointValues)
const juce::String getClientControlParametersAsString ()
const juce::String getIOCountParametersAsString ()
const juce::String getInputMuteParametersAsString ()
const juce::String getOutputMuteParametersAsString ()
const juce::String getCrosspointParametersAsString ()
Protected Member Functions
void changeInputPosition (std::uint16_t channel, std::optional< float > xValOpt, std::optional< float > yValOpt, std::optional< float > sharpnessOpt, std::optional< int > layerOpt, juce::NotificationType notification=juce::dontSendNotification)
void processOutputDistances (std::uint16_t channel, const std::map< juce::AudioChannelSet::ChannelType, float > &channelToOutputsDists)
void selectInputChannel (std::uint16_t channel)
void rebuildControls (bool force=false)
void rebuildInputControls (bool force=false)
Additional Inherited Members
Public Types inherited from Mema::MemaClientControlComponentBase
enum ControlDirection {
None = 0 ,
Input ,
Output
}
Direction of a control strip within the panel layout.
enum ControlsSize {
S = 35 ,
M = 50 ,
L = 65
}
Size category for rendered control elements.
Public Attributes inherited from Mema::MemaClientControlComponentBase
std::function< void(const std::map< std::uint16_t, bool > &)> onInputMutesChanged
std::function< void(const std::map< std::uint16_t, bool > &)> onOutputMutesChanged
std::function< void(const std::map< std::uint16_t, std::map< std::uint16_t, bool > > &)> onCrosspointStatesChanged
std::function< void(const std::map< std::uint16_t, std::map< std::uint16_t, float > > &)> onCrosspointValuesChanged
Static Public Attributes inherited from Mema::MemaClientControlComponentBase
static constexpr int s_gap = 3
static constexpr int s_scrollbarsize = 8
Protected Attributes inherited from Mema::MemaClientControlComponentBase
ControlsSize m_controlsSize = ControlsSize::S
Detailed Description
2-D spatial panning remote control for Mema.Re.
Hosts a TwoDFieldMultisliderComponent for interactive speaker-layout panning and an ADMOSController for receiving external ADM-OSC position/mute updates. Sends updated ControlParametersMessage payloads back to Mema via the onMessageReadyToSend callback.
Definition at line 49 of file PanningControlComponent.h.
Constructor & Destructor Documentation
PanningControlComponent()
Mema::PanningControlComponent::PanningControlComponent ()
Definition at line 32 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::addCrosspointStates(), Mema::MemaClientControlComponentBase::addCrosspointValues(), changeInputPosition(), Mema::MemaClientControlComponentBase::getCrosspointStates(), Mema::MemaClientControlComponentBase::getCrosspointValues(), handleExternalControlParameter(), Mema::MemaClientControlComponentBase::onCrosspointStatesChanged, Mema::MemaClientControlComponentBase::onCrosspointValuesChanged, processOutputDistances(), Mema::MemaClientControlComponentBase::s_gap, and selectInputChannel().
~PanningControlComponent()
Mema::PanningControlComponent::~PanningControlComponent () virtual
Definition at line 79 of file PanningControlComponent.cpp.
Member Function Documentation
changeInputPosition()
void Mema::PanningControlComponent::changeInputPosition (std::uint16_t channel, std::optional< float > xValOpt, std::optional< float > yValOpt, std::optional< float > sharpnessOpt, std::optional< int > layerOpt, juce::NotificationType notification = juce::dontSendNotification) protected
Definition at line 407 of file PanningControlComponent.cpp.
References Mema::ADMOSController::External, Mema::ADMOSController::ADMOSCParameterX::getParameterVal(), Mema::ADMOSController::ADMOSCParameterY::getParameterVal(), Mema::ADMOSController::ADMOSCParameterZ::getParameterVal(), Mema::ADMOSController::ADMOSCParameterWidth::getParameterVal(), Mema::ADMOSController::None, Mema::ADMOSController::Width, Mema::ADMOSController::X, Mema::ADMOSController::Y, and Mema::ADMOSController::Z.
Referenced by handleExternalControlParameter(), and PanningControlComponent().
getChannelConfig()
const juce::AudioChannelSet & Mema::PanningControlComponent::getChannelConfig ()
Definition at line 180 of file PanningControlComponent.cpp.
handleExternalControlParameter()
void Mema::PanningControlComponent::handleExternalControlParameter (int objNum, std::uint16_t objType, void * sender = nullptr)
Definition at line 197 of file PanningControlComponent.cpp.
References changeInputPosition(), Mema::ADMOSController::Empty, Mema::ADMOSController::ADMOSCParameterX::getParameterVal(), Mema::ADMOSController::ADMOSCParameterY::getParameterVal(), Mema::ADMOSController::ADMOSCParameterZ::getParameterVal(), Mema::ADMOSController::ADMOSCParameterWidth::getParameterVal(), Mema::ADMOSController::ADMOSCParameterMute::getParameterVal(), Mema::ADMOSController::ADMOSCParameterXY::getParameterVals(), Mema::ADMOSController::ADMOSCParameterXYZ::getParameterVals(), Mema::ADMOSController::Mute, setInputMuteStates(), Mema::ADMOSController::Width, Mema::ADMOSController::X, Mema::ADMOSController::XY, Mema::ADMOSController::XYZ, Mema::ADMOSController::Y, and Mema::ADMOSController::Z.
Referenced by PanningControlComponent().
lookAndFeelChanged()
void Mema::PanningControlComponent::lookAndFeelChanged () override
Definition at line 127 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::getIOCount().
paint()
void Mema::PanningControlComponent::paint (Graphics &) override virtual
Implements Mema::MemaClientControlComponentBase.
Definition at line 83 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::m_controlsSize, and Mema::MemaClientControlComponentBase::s_gap.
processOutputDistances()
void Mema::PanningControlComponent::processOutputDistances (std::uint16_t channel, const std::map< juce::AudioChannelSet::ChannelType, float > & channelToOutputsDists) protected
Definition at line 471 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::addCrosspointStates(), Mema::MemaClientControlComponentBase::addCrosspointValues(), Mema::MemaClientControlComponentBase::onCrosspointStatesChanged, and Mema::MemaClientControlComponentBase::onCrosspointValuesChanged.
Referenced by PanningControlComponent().
rebuildControls()
void Mema::PanningControlComponent::rebuildControls (bool force = false) protected
Definition at line 185 of file PanningControlComponent.cpp.
References rebuildInputControls(), and resized().
Referenced by selectInputChannel(), setControlsSize(), and setIOCount().
rebuildInputControls()
void Mema::PanningControlComponent::rebuildInputControls (bool force = false) protected
Definition at line 298 of file PanningControlComponent.cpp.
References Mema::ADMOSController::External, Mema::MemaClientControlComponentBase::getInputMuteStates(), Mema::MemaClientControlComponentBase::getIOCount(), Mema::MemaClientControlComponentBase::m_controlsSize, Mema::MemaClientControlComponentBase::onInputMutesChanged, selectInputChannel(), and Mema::MemaClientControlComponentBase::setInputMuteStates().
Referenced by rebuildControls().
resetCtrl()
void Mema::PanningControlComponent::resetCtrl () override virtual
Implements Mema::MemaClientControlComponentBase.
Definition at line 148 of file PanningControlComponent.cpp.
References selectInputChannel(), setCrosspointStates(), setCrosspointValues(), setInputMuteStates(), setIOCount(), and Mema::MemaClientControlComponentBase::setOutputMuteStates().
resized()
void Mema::PanningControlComponent::resized () override virtual
Implements Mema::MemaClientControlComponentBase.
Definition at line 95 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::m_controlsSize, Mema::MemaClientControlComponentBase::s_gap, and Mema::MemaClientControlComponentBase::s_scrollbarsize.
Referenced by rebuildControls().
selectInputChannel()
void Mema::PanningControlComponent::selectInputChannel (std::uint16_t channel) protected
Definition at line 388 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::getIOCount(), and rebuildControls().
Referenced by PanningControlComponent(), rebuildInputControls(), resetCtrl(), setControlsSize(), and setIOCount().
setChannelConfig()
void Mema::PanningControlComponent::setChannelConfig (const juce::AudioChannelSet & channelConfiguration)
Definition at line 172 of file PanningControlComponent.cpp.
setControlsSize()
void Mema::PanningControlComponent::setControlsSize (const ControlsSize & ctrlsSize) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 137 of file PanningControlComponent.cpp.
References rebuildControls(), selectInputChannel(), and Mema::MemaClientControlComponentBase::setControlsSize().
setCrosspointStates()
void Mema::PanningControlComponent::setCrosspointStates (const std::map< std::uint16_t, std::map< std::uint16_t, bool > > & crosspointStates) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 372 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::setCrosspointStates().
Referenced by resetCtrl().
setCrosspointValues()
void Mema::PanningControlComponent::setCrosspointValues (const std::map< std::uint16_t, std::map< std::uint16_t, float > > & crosspointValues) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 380 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::setCrosspointValues().
Referenced by resetCtrl().
setExternalControlSettings()
void Mema::PanningControlComponent::setExternalControlSettings (int ADMOSCPort, const juce::IPAddress & ADMOSCControllerIP, int ADMOSCControllerPort)
Definition at line 191 of file PanningControlComponent.cpp.
setInputMuteStates()
void Mema::PanningControlComponent::setInputMuteStates (const std::map< std::uint16_t, bool > & inputMuteStates) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 358 of file PanningControlComponent.cpp.
References Mema::MemaClientControlComponentBase::setInputMuteStates().
Referenced by handleExternalControlParameter(), and resetCtrl().
setIOCount()
void Mema::PanningControlComponent::setIOCount (const std::pair< int, int > & ioCount) override virtual
Reimplemented from Mema::MemaClientControlComponentBase.
Definition at line 158 of file PanningControlComponent.cpp.
References rebuildControls(), selectInputChannel(), and Mema::MemaClientControlComponentBase::setIOCount().
Referenced by resetCtrl().
The documentation for this class was generated from the following files:
Source/MemaClientCommon/PanningControlComponent.h
Source/MemaClientCommon/PanningControlComponent.cpp