Mema: Mema::MemaInputCommander Class Reference
Mema::MemaInputCommander Class Reference abstract
#include <MemaCommanders.h>
Public Member Functions
MemaInputCommander ()
virtual ~MemaInputCommander () override
void setInputMuteChangeCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t, bool)> &callback)
void setInputLevelChangeCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t, float)> &callback)
void setInputMutePollCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t)> &callback)
void setInputLevelPollCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t)> &callback)
virtual void setInputMute (std::uint16_t channel, bool muteState, int userId=-1)=0
virtual void setInputLevel (std::uint16_t channel, float levelValue, int userId=-1)
Public Member Functions inherited from Mema::MemaChannelCommander
MemaChannelCommander ()
virtual ~MemaChannelCommander ()
virtual void setChannelCount (std::uint16_t channelCount)=0
Protected Member Functions
void inputMuteChange (std::uint16_t channel, bool muteState, MemaInputCommander *sender)
void inputLevelChange (std::uint16_t channel, float levelValue, MemaInputCommander *sender)
void inputMutePoll (std::uint16_t channel, MemaInputCommander *sender)
void inputLevelPoll (std::uint16_t channel, MemaInputCommander *sender)
Detailed Description
interface for an input channel — extends MemaChannelCommander with mute control.
Definition at line 45 of file MemaCommanders.h.
Constructor & Destructor Documentation
MemaInputCommander()
Mema::MemaInputCommander::MemaInputCommander ()
Definition at line 34 of file MemaCommanders.cpp.
~MemaInputCommander()
Mema::MemaInputCommander::~MemaInputCommander () override virtual
Definition at line 38 of file MemaCommanders.cpp.
Member Function Documentation
inputLevelChange()
void Mema::MemaInputCommander::inputLevelChange (std::uint16_t channel, float levelValue, MemaInputCommander * sender) protected
Definition at line 68 of file MemaCommanders.cpp.
inputLevelPoll()
void Mema::MemaInputCommander::inputLevelPoll (std::uint16_t channel, MemaInputCommander * sender) protected
Definition at line 80 of file MemaCommanders.cpp.
inputMuteChange()
void Mema::MemaInputCommander::inputMuteChange (std::uint16_t channel, bool muteState, MemaInputCommander * sender) protected
Definition at line 62 of file MemaCommanders.cpp.
Referenced by Mema::InputControlComponent::buttonClicked().
inputMutePoll()
void Mema::MemaInputCommander::inputMutePoll (std::uint16_t channel, MemaInputCommander * sender) protected
Definition at line 74 of file MemaCommanders.cpp.
setInputLevel()
virtual void Mema::MemaInputCommander::setInputLevel (std::uint16_t channel, float levelValue, int userId = -1) inline virtual
Definition at line 57 of file MemaCommanders.h.
setInputLevelChangeCallback()
void Mema::MemaInputCommander::setInputLevelChangeCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t, float)> & callback)
Definition at line 47 of file MemaCommanders.cpp.
setInputLevelPollCallback()
void Mema::MemaInputCommander::setInputLevelPollCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t)> & callback)
Definition at line 57 of file MemaCommanders.cpp.
setInputMute()
virtual void Mema::MemaInputCommander::setInputMute (std::uint16_t channel, bool muteState, int userId = -1) pure virtual
Implemented in Mema::MemaNetworkClientCommanderWrapper, and Mema::InputControlComponent.
Referenced by Mema::MemaProcessor::initializeInputCommander().
setInputMuteChangeCallback()
void Mema::MemaInputCommander::setInputMuteChangeCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t, bool)> & callback)
Definition at line 42 of file MemaCommanders.cpp.
Referenced by Mema::MemaProcessor::addInputCommander().
setInputMutePollCallback()
void Mema::MemaInputCommander::setInputMutePollCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t)> & callback)
Definition at line 52 of file MemaCommanders.cpp.
The documentation for this class was generated from the following files:
Source/MemaProcessor/MemaCommanders.h
Source/MemaProcessor/MemaCommanders.cpp