Mema: MemaApplication Class Reference
MemaApplication Class Reference
Classes
struct MemaTaskbarComponent
Public Member Functions
MemaApplication ()
~MemaApplication ()
const juce::String getApplicationName () override
const juce::String getApplicationVersion () override
bool moreThanOneInstanceAllowed () override
void initialise (const juce::String &commandLine) override
void shutdown () override
std::unique_ptr< Mema::MemaUIComponent > createAndConnectMemaUIComponent ()
void disconnectAndDeleteMemaUIComponent ()
void showUiAsCalloutBox (const juce::Point< int > &positionToPointTo)
void showUiAsStandaloneWindow ()
Detailed Description
Definition at line 99 of file Main.cpp.
Constructor & Destructor Documentation
MemaApplication()
MemaApplication::MemaApplication () inline
Definition at line 103 of file Main.cpp.
~MemaApplication()
MemaApplication::~MemaApplication () inline
Definition at line 104 of file Main.cpp.
References disconnectAndDeleteMemaUIComponent().
Member Function Documentation
createAndConnectMemaUIComponent()
std::unique_ptr< Mema::MemaUIComponent > MemaApplication::createAndConnectMemaUIComponent () inline
Definition at line 210 of file Main.cpp.
References disconnectAndDeleteMemaUIComponent(), and showUiAsStandaloneWindow().
Referenced by showUiAsCalloutBox(), and showUiAsStandaloneWindow().
disconnectAndDeleteMemaUIComponent()
void MemaApplication::disconnectAndDeleteMemaUIComponent () inline
Definition at line 300 of file Main.cpp.
Referenced by createAndConnectMemaUIComponent(), showUiAsCalloutBox(), and ~MemaApplication().
getApplicationName()
const juce::String MemaApplication::getApplicationName () inline override
Definition at line 110 of file Main.cpp.
Referenced by initialise(), and MemaApplication::MemaTaskbarComponent::MemaTaskbarComponent().
getApplicationVersion()
const juce::String MemaApplication::getApplicationVersion () inline override
Definition at line 111 of file Main.cpp.
initialise()
void MemaApplication::initialise (const juce::String & commandLine) inline override
Definition at line 115 of file Main.cpp.
References getApplicationName(), showUiAsCalloutBox(), and showUiAsStandaloneWindow().
moreThanOneInstanceAllowed()
bool MemaApplication::moreThanOneInstanceAllowed () inline override
Definition at line 112 of file Main.cpp.
showUiAsCalloutBox()
void MemaApplication::showUiAsCalloutBox (const juce::Point< int > & positionToPointTo) inline
Definition at line 313 of file Main.cpp.
References createAndConnectMemaUIComponent(), and disconnectAndDeleteMemaUIComponent().
Referenced by initialise().
showUiAsStandaloneWindow()
void MemaApplication::showUiAsStandaloneWindow () inline
Definition at line 330 of file Main.cpp.
References createAndConnectMemaUIComponent().
Referenced by createAndConnectMemaUIComponent(), and initialise().
shutdown()
void MemaApplication::shutdown () inline override
Definition at line 195 of file Main.cpp.
The documentation for this class was generated from the following file:
Source/Main.cpp