Mema: Mema::MemaOutputCommander Class Reference
Mema::MemaOutputCommander Class Reference abstract
#include <MemaCommanders.h>
Public Member Functions
MemaOutputCommander ()
virtual ~MemaOutputCommander () override
void setOutputMuteChangeCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t, bool)> &callback)
void setOutputLevelChangeCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t, float)> &callback)
void setOutputMutePollCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t)> &callback)
void setOutputLevelPollCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t)> &callback)
virtual void setOutputMute (std::uint16_t channel, bool muteState, int userId=-1)=0
virtual void setOutputLevel (std::uint16_t channel, float levelValue, int userId=-1)
Public Member Functions inherited from Mema::MemaChannelCommander
MemaChannelCommander ()
virtual ~MemaChannelCommander ()
virtual void setChannelCount (std::uint16_t channelCount)=0
Protected Member Functions
void outputMuteChange (std::uint16_t channel, bool muteState, MemaOutputCommander *sender)
void outputLevelChange (std::uint16_t channel, float levelValue, MemaOutputCommander *sender)
void outputMutePoll (std::uint16_t channel, MemaOutputCommander *sender)
void outputLevelPoll (std::uint16_t channel, MemaOutputCommander *sender)
Detailed Description
interface for an output channel — extends MemaChannelCommander with mute control.
Definition at line 76 of file MemaCommanders.h.
Constructor & Destructor Documentation
MemaOutputCommander()
Mema::MemaOutputCommander::MemaOutputCommander ()
Definition at line 87 of file MemaCommanders.cpp.
~MemaOutputCommander()
Mema::MemaOutputCommander::~MemaOutputCommander () override virtual
Definition at line 91 of file MemaCommanders.cpp.
Member Function Documentation
outputLevelChange()
void Mema::MemaOutputCommander::outputLevelChange (std::uint16_t channel, float levelValue, MemaOutputCommander * sender) protected
Definition at line 121 of file MemaCommanders.cpp.
outputLevelPoll()
void Mema::MemaOutputCommander::outputLevelPoll (std::uint16_t channel, MemaOutputCommander * sender) protected
Definition at line 133 of file MemaCommanders.cpp.
outputMuteChange()
void Mema::MemaOutputCommander::outputMuteChange (std::uint16_t channel, bool muteState, MemaOutputCommander * sender) protected
Definition at line 115 of file MemaCommanders.cpp.
Referenced by Mema::OutputControlComponent::buttonClicked().
outputMutePoll()
void Mema::MemaOutputCommander::outputMutePoll (std::uint16_t channel, MemaOutputCommander * sender) protected
Definition at line 127 of file MemaCommanders.cpp.
setOutputLevel()
virtual void Mema::MemaOutputCommander::setOutputLevel (std::uint16_t channel, float levelValue, int userId = -1) inline virtual
Definition at line 88 of file MemaCommanders.h.
setOutputLevelChangeCallback()
void Mema::MemaOutputCommander::setOutputLevelChangeCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t, float)> & callback)
Definition at line 100 of file MemaCommanders.cpp.
setOutputLevelPollCallback()
void Mema::MemaOutputCommander::setOutputLevelPollCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t)> & callback)
Definition at line 110 of file MemaCommanders.cpp.
setOutputMute()
virtual void Mema::MemaOutputCommander::setOutputMute (std::uint16_t channel, bool muteState, int userId = -1) pure virtual
Implemented in Mema::MemaNetworkClientCommanderWrapper, and Mema::OutputControlComponent.
Referenced by Mema::MemaProcessor::initializeOutputCommander().
setOutputMuteChangeCallback()
void Mema::MemaOutputCommander::setOutputMuteChangeCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t, bool)> & callback)
Definition at line 95 of file MemaCommanders.cpp.
Referenced by Mema::MemaProcessor::addOutputCommander().
setOutputMutePollCallback()
void Mema::MemaOutputCommander::setOutputMutePollCallback (const std::function< void(MemaOutputCommander *sender, std::uint16_t)> & callback)
Definition at line 105 of file MemaCommanders.cpp.
The documentation for this class was generated from the following files:
Source/MemaProcessor/MemaCommanders.h
Source/MemaProcessor/MemaCommanders.cpp