Mema: Mema::ProcessorSpectrumData Class Reference
Mema::ProcessorSpectrumData Class Reference
#include <ProcessorSpectrumData.h>
Classes
struct SpectrumBands
FFT output for a single channel — 512 frequency bins with peak and hold values.
Public Member Functions
ProcessorSpectrumData ()
~ProcessorSpectrumData ()
void SetSpectrum (unsigned long channel, SpectrumBands spectrum)
const SpectrumBands & GetSpectrum (unsigned long channel)
void SetChannelCount (unsigned long count) override
Sets the number of audio channels this data object covers.
unsigned long GetChannelCount () override
Returns the number of audio channels this data object covers.
Public Member Functions inherited from Mema::AbstractProcessorData
AbstractProcessorData ()
virtual ~AbstractProcessorData ()
Type GetDataType ()
Returns the concrete type of this data object.
Additional Inherited Members
Public Types inherited from Mema::AbstractProcessorData
enum Type {
Invalid ,
AudioSignal ,
Level ,
Spectrum
}
Identifies the concrete payload type carried by this data object.
Protected Attributes inherited from Mema::AbstractProcessorData
Type m_type
Detailed Description
data object carrying FFT magnitude bins for each channel.
Definition at line 26 of file ProcessorSpectrumData.h.
Constructor & Destructor Documentation
ProcessorSpectrumData()
Mema::ProcessorSpectrumData::ProcessorSpectrumData ()
Definition at line 24 of file ProcessorSpectrumData.cpp.
References Mema::AbstractProcessorData::m_type, and Mema::AbstractProcessorData::Spectrum.
~ProcessorSpectrumData()
Mema::ProcessorSpectrumData::~ProcessorSpectrumData ()
Definition at line 29 of file ProcessorSpectrumData.cpp.
Member Function Documentation
GetChannelCount()
unsigned long Mema::ProcessorSpectrumData::GetChannelCount () override virtual
Returns the number of audio channels this data object covers.
Implements Mema::AbstractProcessorData.
Definition at line 59 of file ProcessorSpectrumData.cpp.
Referenced by Mema::SpectrumAudioComponent::processingDataChanged(), and SetChannelCount().
GetSpectrum()
const ProcessorSpectrumData::SpectrumBands & Mema::ProcessorSpectrumData::GetSpectrum (unsigned long channel)
Definition at line 39 of file ProcessorSpectrumData.cpp.
Referenced by Mema::SpectrumAudioComponent::processingDataChanged().
SetChannelCount()
void Mema::ProcessorSpectrumData::SetChannelCount (unsigned long count) override virtual
Sets the number of audio channels this data object covers.
Implements Mema::AbstractProcessorData.
Definition at line 47 of file ProcessorSpectrumData.cpp.
References GetChannelCount().
SetSpectrum()
void Mema::ProcessorSpectrumData::SetSpectrum (unsigned long channel, ProcessorSpectrumData::SpectrumBands spectrum)
Definition at line 34 of file ProcessorSpectrumData.cpp.
The documentation for this class was generated from the following files:
Source/MemaProcessor/ProcessorSpectrumData.h
Source/MemaProcessor/ProcessorSpectrumData.cpp