Mema: Mema::MeterbridgeComponent Class Reference
Mema::MeterbridgeComponent Class Reference
#include <MeterbridgeComponent.h>
Public Types
enum Direction {
Horizontal ,
Vertical
}
Orientation of the meter bars.
Public Member Functions
MeterbridgeComponent ()
MeterbridgeComponent (Direction direction)
~MeterbridgeComponent ()
void paint (Graphics &) override
void processingDataChanged (AbstractProcessorData *data) override
void setDirection (Direction direction)
void setChannelCount (int channelCount)
int getChannelCount ()
Public Member Functions inherited from Mema::AbstractAudioVisualizer
AbstractAudioVisualizer ()
virtual ~AbstractAudioVisualizer ()
void notifyChanges ()
Marks that new data is available and triggers a repaint on the next timer tick.
virtual void processChanges ()
Called on the message thread to update cached data before repainting.
void paint (Graphics &) override
Paints the visualiser background.
void resized () override
Lays out child components.
void mouseDown (const MouseEvent &event) override
Handles mouse-down events (e.g. right-click context menu).
void setRefreshFrequency (int frequency)
Sets the display refresh rate in Hz.
void timerCallback () override
Timer callback that calls processChanges() and triggers a repaint if data changed.
Public Member Functions inherited from Mema::ProcessorDataAnalyzer::Listener
virtual ~Listener ()
Additional Inherited Members
Protected Member Functions inherited from Mema::AbstractAudioVisualizer
void setUsesValuesInDB (bool useValuesInDB)
bool getUsesValuesInDB ()
Detailed Description
bar component supporting horizontal and vertical orientations.
Definition at line 30 of file MeterbridgeComponent.h.
Member Enumeration Documentation
Direction
enum Mema::MeterbridgeComponent::Direction
Orientation of the meter bars.
Enumerator
Horizontal
Bars grow left-to-right.
Vertical
Bars grow bottom-to-top.
Definition at line 34 of file MeterbridgeComponent.h.
Constructor & Destructor Documentation
MeterbridgeComponent() [1/2]
Mema::MeterbridgeComponent::MeterbridgeComponent ()
Definition at line 27 of file MeterbridgeComponent.cpp.
References Mema::ProcessorLevelData::LevelVal::GetFactorHOLDdB(), Mema::ProcessorLevelData::LevelVal::GetFactorPEAKdB(), Mema::ProcessorLevelData::LevelVal::GetFactorRMSdB(), Mema::AbstractAudioVisualizer::setRefreshFrequency(), and Mema::AbstractAudioVisualizer::setUsesValuesInDB().
MeterbridgeComponent() [2/2]
Mema::MeterbridgeComponent::MeterbridgeComponent (Direction direction)
Definition at line 61 of file MeterbridgeComponent.cpp.
References setDirection().
~MeterbridgeComponent()
Mema::MeterbridgeComponent::~MeterbridgeComponent ()
Definition at line 67 of file MeterbridgeComponent.cpp.
Member Function Documentation
getChannelCount()
int Mema::MeterbridgeComponent::getChannelCount ()
Definition at line 242 of file MeterbridgeComponent.cpp.
paint()
void Mema::MeterbridgeComponent::paint (Graphics & g) override
Definition at line 72 of file MeterbridgeComponent.cpp.
References Mema::ProcessorLevelData::LevelVal::GetFactorPEAKdB(), Mema::ProcessorDataAnalyzer::getGlobalMaxdB(), Mema::ProcessorDataAnalyzer::getGlobalMindB(), Mema::ProcessorLevelData::GetLevel(), Mema::AbstractAudioVisualizer::getUsesValuesInDB(), and Horizontal.
processingDataChanged()
void Mema::MeterbridgeComponent::processingDataChanged (AbstractProcessorData * data) override virtual
Implements Mema::ProcessorDataAnalyzer::Listener.
Definition at line 212 of file MeterbridgeComponent.cpp.
References Mema::AbstractProcessorData::AudioSignal, Mema::AbstractProcessorData::GetDataType(), Mema::AbstractProcessorData::Invalid, Mema::AbstractProcessorData::Level, Mema::AbstractAudioVisualizer::notifyChanges(), and Mema::AbstractProcessorData::Spectrum.
setChannelCount()
void Mema::MeterbridgeComponent::setChannelCount (int channelCount)
Definition at line 237 of file MeterbridgeComponent.cpp.
setDirection()
void Mema::MeterbridgeComponent::setDirection (Direction direction)
Definition at line 231 of file MeterbridgeComponent.cpp.
Referenced by MeterbridgeComponent().
The documentation for this class was generated from the following files:
Source/MemaProcessorEditor/MeterbridgeComponent.h
Source/MemaProcessorEditor/MeterbridgeComponent.cpp