Mema: Mema::SpectrumAudioComponent Class Reference
Mema::SpectrumAudioComponent Class Reference
#include <SpectrumAudioComponent.h>
Classes
struct PlotPoints
Cached per-channel FFT peak and hold data ready for painting.
Public Member Functions
SpectrumAudioComponent ()
~SpectrumAudioComponent ()
void setNumVisibleChannels (int numChannels)
int getNumVisibleChannels ()
void paint (juce::Graphics &) override
void resized () override
void lookAndFeelChanged () override
void processingDataChanged (AbstractProcessorData *data) override
Public Member Functions inherited from Mema::AbstractAudioVisualizer
AbstractAudioVisualizer ()
virtual ~AbstractAudioVisualizer ()
void notifyChanges ()
Marks that new data is available and triggers a repaint on the next timer tick.
virtual void processChanges ()
Called on the message thread to update cached data before repainting.
void paint (Graphics &) override
Paints the visualiser background.
void resized () override
Lays out child components.
void mouseDown (const MouseEvent &event) override
Handles mouse-down events (e.g. right-click context menu).
void setRefreshFrequency (int frequency)
Sets the display refresh rate in Hz.
void timerCallback () override
Timer callback that calls processChanges() and triggers a repaint if data changed.
Public Member Functions inherited from Mema::ProcessorDataAnalyzer::Listener
virtual ~Listener ()
Additional Inherited Members
Protected Member Functions inherited from Mema::AbstractAudioVisualizer
void setUsesValuesInDB (bool useValuesInDB)
bool getUsesValuesInDB ()
Detailed Description
frequency-spectrum visualisation component for Mema.Mo.
Definition at line 31 of file SpectrumAudioComponent.h.
Constructor & Destructor Documentation
SpectrumAudioComponent()
Mema::SpectrumAudioComponent::SpectrumAudioComponent ()
Definition at line 31 of file SpectrumAudioComponent.cpp.
References lookAndFeelChanged(), setNumVisibleChannels(), and Mema::AbstractAudioVisualizer::setRefreshFrequency().
~SpectrumAudioComponent()
Mema::SpectrumAudioComponent::~SpectrumAudioComponent ()
Definition at line 56 of file SpectrumAudioComponent.cpp.
Member Function Documentation
getNumVisibleChannels()
int Mema::SpectrumAudioComponent::getNumVisibleChannels ()
Definition at line 326 of file SpectrumAudioComponent.cpp.
Referenced by paint(), and processingDataChanged().
lookAndFeelChanged()
void Mema::SpectrumAudioComponent::lookAndFeelChanged () override
Definition at line 260 of file SpectrumAudioComponent.cpp.
Referenced by SpectrumAudioComponent().
paint()
void Mema::SpectrumAudioComponent::paint (juce::Graphics & g) override
Definition at line 60 of file SpectrumAudioComponent.cpp.
References Mema::ProcessorDataAnalyzer::getGlobalMaxdB(), Mema::ProcessorDataAnalyzer::getGlobalMindB(), getNumVisibleChannels(), and Mema::AbstractAudioVisualizer::paint().
processingDataChanged()
void Mema::SpectrumAudioComponent::processingDataChanged (AbstractProcessorData * data) override virtual
Implements Mema::ProcessorDataAnalyzer::Listener.
Definition at line 267 of file SpectrumAudioComponent.cpp.
References Mema::AbstractProcessorData::AudioSignal, Mema::ProcessorSpectrumData::GetChannelCount(), Mema::AbstractProcessorData::GetDataType(), getNumVisibleChannels(), Mema::ProcessorSpectrumData::GetSpectrum(), Mema::AbstractProcessorData::Invalid, Mema::AbstractProcessorData::Level, Mema::AbstractAudioVisualizer::notifyChanges(), setNumVisibleChannels(), and Mema::AbstractProcessorData::Spectrum.
resized()
void Mema::SpectrumAudioComponent::resized () override
Definition at line 247 of file SpectrumAudioComponent.cpp.
References Mema::AbstractAudioVisualizer::resized().
setNumVisibleChannels()
void Mema::SpectrumAudioComponent::setNumVisibleChannels (int numChannels)
Definition at line 320 of file SpectrumAudioComponent.cpp.
Referenced by processingDataChanged(), and SpectrumAudioComponent().
The documentation for this class was generated from the following files:
Source/MemaClientCommon/SpectrumAudioComponent.h
Source/MemaClientCommon/SpectrumAudioComponent.cpp