Mema: Mema::CrosspointComponent Class Reference
Mema::CrosspointComponent Class Reference
#include <CrosspointsControlComponent.h>
Public Types
using CrosspointIdent = std::pair< int, int >
Public Member Functions
CrosspointComponent (const CrosspointIdent &ident)
~CrosspointComponent ()
const CrosspointIdent & getIdent ()
void paint (Graphics &g) override
void setChecked (bool checked)
void toggleChecked ()
void setFactor (float factor)
float getFactor ()
void mouseUp (const MouseEvent &e) override
void mouseDrag (const MouseEvent &e) override
Public Attributes
std::function< void(bool, CrosspointComponent *)> onCheckedChanged
std::function< void(float, CrosspointComponent *)> onFactorChanged
Static Public Attributes
static constexpr auto pi = juce::MathConstants<float>::pi
static constexpr auto arcStartRad = 0.0f
Detailed Description
node in the crosspoint matrix — draggable to set gain, clickable to toggle enable.
Definition at line 33 of file CrosspointsControlComponent.h.
Member Typedef Documentation
CrosspointIdent
using Mema::CrosspointComponent::CrosspointIdent = std::pair<int, int>
Definition at line 36 of file CrosspointsControlComponent.h.
Constructor & Destructor Documentation
CrosspointComponent()
Mema::CrosspointComponent::CrosspointComponent (const CrosspointIdent & ident) inline
Definition at line 42 of file CrosspointsControlComponent.h.
~CrosspointComponent()
Mema::CrosspointComponent::~CrosspointComponent () inline
Definition at line 43 of file CrosspointsControlComponent.h.
Member Function Documentation
getFactor()
float Mema::CrosspointComponent::getFactor () inline
Definition at line 102 of file CrosspointsControlComponent.h.
getIdent()
const CrosspointIdent & Mema::CrosspointComponent::getIdent () inline
Definition at line 45 of file CrosspointsControlComponent.h.
mouseDrag()
void Mema::CrosspointComponent::mouseDrag (const MouseEvent & e) inline override
Definition at line 126 of file CrosspointsControlComponent.h.
References Mema::ProcessorDataAnalyzer::getGlobalMindB(), and onFactorChanged.
mouseUp()
void Mema::CrosspointComponent::mouseUp (const MouseEvent & e) inline override
Definition at line 108 of file CrosspointsControlComponent.h.
References onFactorChanged, and toggleChecked().
paint()
void Mema::CrosspointComponent::paint (Graphics & g) inline override
Definition at line 48 of file CrosspointsControlComponent.h.
References arcStartRad, Mema::ProcessorDataAnalyzer::getGlobalMindB(), and pi.
setChecked()
void Mema::CrosspointComponent::setChecked (bool checked) inline
Definition at line 81 of file CrosspointsControlComponent.h.
Referenced by toggleChecked().
setFactor()
void Mema::CrosspointComponent::setFactor (float factor) inline
Definition at line 97 of file CrosspointsControlComponent.h.
toggleChecked()
void Mema::CrosspointComponent::toggleChecked () inline
Definition at line 86 of file CrosspointsControlComponent.h.
References onCheckedChanged, onFactorChanged, and setChecked().
Referenced by mouseUp().
Member Data Documentation
arcStartRad
constexpr auto Mema::CrosspointComponent::arcStartRad = 0.0f static constexpr
Definition at line 39 of file CrosspointsControlComponent.h.
Referenced by paint().
onCheckedChanged
std::function<void(bool, CrosspointComponent*)> Mema::CrosspointComponent::onCheckedChanged
Definition at line 155 of file CrosspointsControlComponent.h.
Referenced by toggleChecked().
onFactorChanged
std::function<void(float, CrosspointComponent*)> Mema::CrosspointComponent::onFactorChanged
Definition at line 156 of file CrosspointsControlComponent.h.
Referenced by mouseDrag(), mouseUp(), and toggleChecked().
pi
constexpr auto Mema::CrosspointComponent::pi = juce::MathConstants<float>::pi static constexpr
Definition at line 38 of file CrosspointsControlComponent.h.
Referenced by paint().
The documentation for this class was generated from the following file:
Source/MemaProcessorEditor/CrosspointsControlComponent.h