Mema: Mema::MemaCrosspointCommander Class Reference
Mema::MemaCrosspointCommander Class Reference abstract
#include <MemaCommanders.h>
Public Member Functions
MemaCrosspointCommander ()
virtual ~MemaCrosspointCommander () override
void setCrosspointEnabledChangeCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t, bool)> &callback)
void setCrosspointEnabledPollCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t)> &callback)
virtual void setCrosspointEnabledValue (std::uint16_t input, std::uint16_t output, bool enabledState, int userId=-1)=0
void setCrosspointFactorChangeCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t, float)> &callback)
void setCrosspointFactorPollCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t)> &callback)
virtual void setCrosspointFactorValue (std::uint16_t input, std::uint16_t output, float factor, int userId=-1)=0
virtual void setIOCount (std::uint16_t inputCount, std::uint16_t outputCount)=0
Public Member Functions inherited from Mema::MemaChannelCommander
MemaChannelCommander ()
virtual ~MemaChannelCommander ()
Protected Member Functions
void crosspointEnabledChange (std::uint16_t input, std::uint16_t output, bool enabledState, MemaCrosspointCommander *sender)
void crosspointEnabledPoll (std::uint16_t input, std::uint16_t output, MemaCrosspointCommander *sender)
void crosspointFactorChange (std::uint16_t input, std::uint16_t output, float factor, MemaCrosspointCommander *sender)
void crosspointFactorPoll (std::uint16_t input, std::uint16_t output, MemaCrosspointCommander *sender)
Detailed Description
interface for a crosspoint node — controls enable state and gain.
Definition at line 108 of file MemaCommanders.h.
Constructor & Destructor Documentation
MemaCrosspointCommander()
Mema::MemaCrosspointCommander::MemaCrosspointCommander ()
Definition at line 140 of file MemaCommanders.cpp.
~MemaCrosspointCommander()
Mema::MemaCrosspointCommander::~MemaCrosspointCommander () override virtual
Definition at line 144 of file MemaCommanders.cpp.
Member Function Documentation
crosspointEnabledChange()
void Mema::MemaCrosspointCommander::crosspointEnabledChange (std::uint16_t input, std::uint16_t output, bool enabledState, MemaCrosspointCommander * sender) protected
Definition at line 158 of file MemaCommanders.cpp.
Referenced by Mema::CrosspointsControlComponent::setIOCount().
crosspointEnabledPoll()
void Mema::MemaCrosspointCommander::crosspointEnabledPoll (std::uint16_t input, std::uint16_t output, MemaCrosspointCommander * sender) protected
Definition at line 164 of file MemaCommanders.cpp.
crosspointFactorChange()
void Mema::MemaCrosspointCommander::crosspointFactorChange (std::uint16_t input, std::uint16_t output, float factor, MemaCrosspointCommander * sender) protected
Definition at line 180 of file MemaCommanders.cpp.
Referenced by Mema::CrosspointsControlComponent::setIOCount().
crosspointFactorPoll()
void Mema::MemaCrosspointCommander::crosspointFactorPoll (std::uint16_t input, std::uint16_t output, MemaCrosspointCommander * sender) protected
Definition at line 186 of file MemaCommanders.cpp.
setCrosspointEnabledChangeCallback()
void Mema::MemaCrosspointCommander::setCrosspointEnabledChangeCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t, bool)> & callback)
Definition at line 148 of file MemaCommanders.cpp.
Referenced by Mema::MemaProcessor::addCrosspointCommander().
setCrosspointEnabledPollCallback()
void Mema::MemaCrosspointCommander::setCrosspointEnabledPollCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t)> & callback)
Definition at line 153 of file MemaCommanders.cpp.
setCrosspointEnabledValue()
virtual void Mema::MemaCrosspointCommander::setCrosspointEnabledValue (std::uint16_t input, std::uint16_t output, bool enabledState, int userId = -1) pure virtual
Implemented in Mema::MemaNetworkClientCommanderWrapper, and Mema::CrosspointsControlComponent.
Referenced by Mema::MemaProcessor::initializeCrosspointCommander().
setCrosspointFactorChangeCallback()
void Mema::MemaCrosspointCommander::setCrosspointFactorChangeCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t, float)> & callback)
Definition at line 170 of file MemaCommanders.cpp.
Referenced by Mema::MemaProcessor::addCrosspointCommander().
setCrosspointFactorPollCallback()
void Mema::MemaCrosspointCommander::setCrosspointFactorPollCallback (const std::function< void(MemaCrosspointCommander *sender, std::uint16_t, std::uint16_t)> & callback)
Definition at line 175 of file MemaCommanders.cpp.
setCrosspointFactorValue()
virtual void Mema::MemaCrosspointCommander::setCrosspointFactorValue (std::uint16_t input, std::uint16_t output, float factor, int userId = -1) pure virtual
Implemented in Mema::MemaNetworkClientCommanderWrapper, and Mema::CrosspointsControlComponent.
Referenced by Mema::MemaProcessor::initializeCrosspointCommander().
setIOCount()
virtual void Mema::MemaCrosspointCommander::setIOCount (std::uint16_t inputCount, std::uint16_t outputCount) pure virtual
Implemented in Mema::MemaNetworkClientCommanderWrapper, and Mema::CrosspointsControlComponent.
The documentation for this class was generated from the following files:
Source/MemaProcessor/MemaCommanders.h
Source/MemaProcessor/MemaCommanders.cpp