Mema: Mema::ProcessorDataAnalyzer Class Reference
Mema::ProcessorDataAnalyzer Class Reference
Analyses a stream of audio buffers and broadcasts level and spectrum data to registered listeners.
#include <ProcessorDataAnalyzer.h>
Classes
class Listener
Public Types
enum dBRange {
min = -80 ,
max = 0
}
Public Member Functions
ProcessorDataAnalyzer ()
~ProcessorDataAnalyzer ()
void setUseProcessingTypes (bool useLevelProcessing, bool useBufferProcessing, bool useSepctrumProcessing)
Configures which data types (level, spectrum, audio signal) the analyzer computes.
bool isLevelProcessingUsed ()
bool isBufferProcessingUsed ()
bool isSepctrumProcessingUsed ()
void initializeParameters (double sampleRate, int bufferSize)
void clearParameters ()
void setHoldTime (int holdTimeMs)
ProcessorAudioSignalData & GetCentiSecondBuffer ()
ProcessorLevelData & GetLevel ()
ProcessorSpectrumData & GetSpectrum ()
juce::String & GetName ()
bool IsInitialized ()
void addListener (Listener *listener)
void removeListener (Listener *listener)
void analyzeData (const juce::AudioBuffer< float > &buffer)
Submits a new audio buffer for analysis.
void timerCallback () override
Timer callback that broadcasts pending data changes to all registered listeners.
Static Public Member Functions
static int getGlobalMindB ()
static int getGlobalMaxdB ()
Detailed Description
Analyses a stream of audio buffers and broadcasts level and spectrum data to registered listeners.
Definition at line 34 of file ProcessorDataAnalyzer.h.
Member Enumeration Documentation
dBRange
enum Mema::ProcessorDataAnalyzer::dBRange
Enumerator
min
max
Definition at line 84 of file ProcessorDataAnalyzer.h.
Constructor & Destructor Documentation
ProcessorDataAnalyzer()
Mema::ProcessorDataAnalyzer::ProcessorDataAnalyzer ()
Definition at line 26 of file ProcessorDataAnalyzer.cpp.
References setHoldTime().
~ProcessorDataAnalyzer()
Mema::ProcessorDataAnalyzer::~ProcessorDataAnalyzer ()
Definition at line 33 of file ProcessorDataAnalyzer.cpp.
Member Function Documentation
addListener()
void Mema::ProcessorDataAnalyzer::addListener (Listener * listener)
Definition at line 85 of file ProcessorDataAnalyzer.cpp.
analyzeData()
void Mema::ProcessorDataAnalyzer::analyzeData (const juce::AudioBuffer< float > & buffer)
Submits a new audio buffer for analysis.
Definition at line 97 of file ProcessorDataAnalyzer.cpp.
References getGlobalMindB(), Mema::ProcessorLevelData::GetLevel(), Mema::ProcessorAudioSignalData::GetSampleRate(), Mema::ProcessorLevelData::LevelVal::hold, isBufferProcessingUsed(), IsInitialized(), isLevelProcessingUsed(), isSepctrumProcessingUsed(), Mema::ProcessorLevelData::SetLevel(), and Mema::ProcessorAudioSignalData::SetSampleRate().
clearParameters()
void Mema::ProcessorDataAnalyzer::clearParameters ()
Definition at line 69 of file ProcessorDataAnalyzer.cpp.
GetCentiSecondBuffer()
ProcessorAudioSignalData & Mema::ProcessorDataAnalyzer::GetCentiSecondBuffer () inline
Definition at line 64 of file ProcessorDataAnalyzer.h.
getGlobalMaxdB()
static int Mema::ProcessorDataAnalyzer::getGlobalMaxdB () inline static
Definition at line 95 of file ProcessorDataAnalyzer.h.
References max.
Referenced by Mema::TwoDFieldOutputComponent::paint(), Mema::MeterbridgeComponent::paint(), and Mema::SpectrumAudioComponent::paint().
getGlobalMindB()
static int Mema::ProcessorDataAnalyzer::getGlobalMindB () inline static
Definition at line 90 of file ProcessorDataAnalyzer.h.
References min.
Referenced by analyzeData(), Mema::CrosspointComponent::mouseDrag(), Mema::TwoDFieldOutputComponent::paint(), Mema::MeterbridgeComponent::paint(), Mema::CrosspointComponent::paint(), Mema::SpectrumAudioComponent::paint(), Mema::FaderbankControlComponent::rebuildCrosspointControls(), and Mema::TwoDFieldMultisliderComponent::selectInput().
GetLevel()
ProcessorLevelData & Mema::ProcessorDataAnalyzer::GetLevel () inline
Definition at line 65 of file ProcessorDataAnalyzer.h.
GetName()
juce::String & Mema::ProcessorDataAnalyzer::GetName () inline
Definition at line 67 of file ProcessorDataAnalyzer.h.
GetSpectrum()
ProcessorSpectrumData & Mema::ProcessorDataAnalyzer::GetSpectrum () inline
Definition at line 66 of file ProcessorDataAnalyzer.h.
initializeParameters()
void Mema::ProcessorDataAnalyzer::initializeParameters (double sampleRate, int bufferSize)
Definition at line 60 of file ProcessorDataAnalyzer.cpp.
isBufferProcessingUsed()
bool Mema::ProcessorDataAnalyzer::isBufferProcessingUsed ()
Definition at line 50 of file ProcessorDataAnalyzer.cpp.
Referenced by analyzeData().
IsInitialized()
bool Mema::ProcessorDataAnalyzer::IsInitialized () inline
Definition at line 69 of file ProcessorDataAnalyzer.h.
Referenced by analyzeData().
isLevelProcessingUsed()
bool Mema::ProcessorDataAnalyzer::isLevelProcessingUsed ()
Definition at line 45 of file ProcessorDataAnalyzer.cpp.
Referenced by analyzeData().
isSepctrumProcessingUsed()
bool Mema::ProcessorDataAnalyzer::isSepctrumProcessingUsed ()
Definition at line 55 of file ProcessorDataAnalyzer.cpp.
Referenced by analyzeData().
removeListener()
void Mema::ProcessorDataAnalyzer::removeListener (Listener * listener)
Definition at line 91 of file ProcessorDataAnalyzer.cpp.
setHoldTime()
void Mema::ProcessorDataAnalyzer::setHoldTime (int holdTimeMs)
Definition at line 78 of file ProcessorDataAnalyzer.cpp.
Referenced by ProcessorDataAnalyzer().
setUseProcessingTypes()
void Mema::ProcessorDataAnalyzer::setUseProcessingTypes (bool useLevelProcessing, bool useBufferProcessing, bool useSepctrumProcessing)
Configures which data types (level, spectrum, audio signal) the analyzer computes.
Definition at line 38 of file ProcessorDataAnalyzer.cpp.
timerCallback()
void Mema::ProcessorDataAnalyzer::timerCallback () override
Timer callback that broadcasts pending data changes to all registered listeners.
Definition at line 318 of file ProcessorDataAnalyzer.cpp.
The documentation for this class was generated from the following files:
Source/MemaProcessor/ProcessorDataAnalyzer.h
Source/MemaProcessor/ProcessorDataAnalyzer.cpp