Mema: Mema::InputControlComponent Class Reference
Mema::InputControlComponent Class Reference
Input-channel control strip — shows level meters and mute buttons for all input channels.
#include <InputControlComponent.h>
Public Member Functions
InputControlComponent ()
~InputControlComponent ()
void paint (Graphics &) override
void resized () override
void processingDataChanged (AbstractProcessorData *data) override
virtual void processChanges () override
Called on the message thread to update cached data before repainting.
void setInputMute (std::uint16_t channel, bool muteState, int userId=-1) override
void buttonClicked (juce::Button *) override
juce::Rectangle< int > getRequiredSize ()
void setChannelCount (std::uint16_t channelCount) override
Public Member Functions inherited from Mema::AbstractAudioVisualizer
AbstractAudioVisualizer ()
virtual ~AbstractAudioVisualizer ()
void notifyChanges ()
Marks that new data is available and triggers a repaint on the next timer tick.
void paint (Graphics &) override
Paints the visualiser background.
void resized () override
Lays out child components.
void mouseDown (const MouseEvent &event) override
Handles mouse-down events (e.g. right-click context menu).
void setRefreshFrequency (int frequency)
Sets the display refresh rate in Hz.
void timerCallback () override
Timer callback that calls processChanges() and triggers a repaint if data changed.
Public Member Functions inherited from Mema::ProcessorDataAnalyzer::Listener
virtual ~Listener ()
Public Member Functions inherited from Mema::MemaInputCommander
MemaInputCommander ()
virtual ~MemaInputCommander () override
void setInputMuteChangeCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t, bool)> &callback)
void setInputLevelChangeCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t, float)> &callback)
void setInputMutePollCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t)> &callback)
void setInputLevelPollCallback (const std::function< void(MemaInputCommander *sender, std::uint16_t)> &callback)
virtual void setInputLevel (std::uint16_t channel, float levelValue, int userId=-1)
Public Member Functions inherited from Mema::MemaChannelCommander
MemaChannelCommander ()
virtual ~MemaChannelCommander ()
Public Attributes
std::function< void()> onBoundsRequirementChange
Additional Inherited Members
Protected Member Functions inherited from Mema::AbstractAudioVisualizer
void setUsesValuesInDB (bool useValuesInDB)
bool getUsesValuesInDB ()
Protected Member Functions inherited from Mema::MemaInputCommander
void inputMuteChange (std::uint16_t channel, bool muteState, MemaInputCommander *sender)
void inputLevelChange (std::uint16_t channel, float levelValue, MemaInputCommander *sender)
void inputMutePoll (std::uint16_t channel, MemaInputCommander *sender)
void inputLevelPoll (std::uint16_t channel, MemaInputCommander *sender)
Detailed Description
Input-channel control strip — shows level meters and mute buttons for all input channels.
Inherits AbstractAudioVisualizer (receives input analyzer data) and MemaInputCommander (sends mute commands back to MemaProcessor).
Definition at line 41 of file InputControlComponent.h.
Constructor & Destructor Documentation
InputControlComponent()
Mema::InputControlComponent::InputControlComponent ()
Definition at line 28 of file InputControlComponent.cpp.
References Mema::MeterbridgeComponent::Horizontal, and Mema::AbstractAudioVisualizer::setUsesValuesInDB().
~InputControlComponent()
Mema::InputControlComponent::~InputControlComponent ()
Definition at line 37 of file InputControlComponent.cpp.
Member Function Documentation
buttonClicked()
void Mema::InputControlComponent::buttonClicked (juce::Button * button) override
Definition at line 150 of file InputControlComponent.cpp.
References Mema::MemaInputCommander::inputMuteChange().
getRequiredSize()
juce::Rectangle< int > Mema::InputControlComponent::getRequiredSize ()
Definition at line 157 of file InputControlComponent.cpp.
paint()
void Mema::InputControlComponent::paint (Graphics & g) override
Definition at line 63 of file InputControlComponent.cpp.
References Mema::AbstractAudioVisualizer::paint().
processChanges()
void Mema::InputControlComponent::processChanges () override virtual
Called on the message thread to update cached data before repainting.
Reimplemented from Mema::AbstractAudioVisualizer.
Definition at line 100 of file InputControlComponent.cpp.
References Mema::AbstractAudioVisualizer::processChanges().
processingDataChanged()
void Mema::InputControlComponent::processingDataChanged (AbstractProcessorData * data) override virtual
Implements Mema::ProcessorDataAnalyzer::Listener.
Definition at line 81 of file InputControlComponent.cpp.
References Mema::AbstractProcessorData::AudioSignal, Mema::AbstractProcessorData::GetDataType(), Mema::AbstractProcessorData::Invalid, Mema::AbstractProcessorData::Level, Mema::AbstractAudioVisualizer::notifyChanges(), and Mema::AbstractProcessorData::Spectrum.
resized()
void Mema::InputControlComponent::resized () override
Definition at line 42 of file InputControlComponent.cpp.
References Mema::AbstractAudioVisualizer::resized().
Referenced by setChannelCount().
setChannelCount()
void Mema::InputControlComponent::setChannelCount (std::uint16_t channelCount) override virtual
Implements Mema::MemaChannelCommander.
Definition at line 108 of file InputControlComponent.cpp.
References onBoundsRequirementChange, and resized().
setInputMute()
void Mema::InputControlComponent::setInputMute (std::uint16_t channel, bool muteState, int userId = -1) override virtual
Implements Mema::MemaInputCommander.
Definition at line 72 of file InputControlComponent.cpp.
Member Data Documentation
onBoundsRequirementChange
std::function<void()> Mema::InputControlComponent::onBoundsRequirementChange
Definition at line 67 of file InputControlComponent.h.
Referenced by setChannelCount().
The documentation for this class was generated from the following files:
Source/MemaProcessorEditor/InputControlComponent.h
Source/MemaProcessorEditor/InputControlComponent.cpp