Mema: Mema::InterprocessConnectionImpl Class Reference
Mema::InterprocessConnectionImpl Class Reference
Client-side TCP connection wrapper that forwards JUCE IPC events to std::function callbacks.
#include <InterprocessConnection.h>
Public Member Functions
InterprocessConnectionImpl (int id)
virtual ~InterprocessConnectionImpl ()
void connectionMade () override
void connectionLost () override
void messageReceived (const MemoryBlock &message) override
int getId ()
Public Attributes
std::function< void(int)> onConnectionMade
std::function< void(int)> onConnectionLost
std::function< void(int, const MemoryBlock &)> onMessageReceived
Detailed Description
Client-side TCP connection wrapper that forwards JUCE IPC events to std::function callbacks.
Definition at line 31 of file InterprocessConnection.h.
Constructor & Destructor Documentation
InterprocessConnectionImpl()
Mema::InterprocessConnectionImpl::InterprocessConnectionImpl (int id)
Definition at line 27 of file InterprocessConnection.cpp.
~InterprocessConnectionImpl()
Mema::InterprocessConnectionImpl::~InterprocessConnectionImpl () virtual
Definition at line 32 of file InterprocessConnection.cpp.
Member Function Documentation
connectionLost()
void Mema::InterprocessConnectionImpl::connectionLost () override
Definition at line 43 of file InterprocessConnection.cpp.
References onConnectionLost.
connectionMade()
void Mema::InterprocessConnectionImpl::connectionMade () override
Definition at line 37 of file InterprocessConnection.cpp.
References onConnectionMade.
getId()
int Mema::InterprocessConnectionImpl::getId ()
Definition at line 55 of file InterprocessConnection.cpp.
messageReceived()
void Mema::InterprocessConnectionImpl::messageReceived (const MemoryBlock & message) override
Definition at line 49 of file InterprocessConnection.cpp.
References onMessageReceived.
Member Data Documentation
onConnectionLost
std::function<void(int)> Mema::InterprocessConnectionImpl::onConnectionLost
Definition at line 46 of file InterprocessConnection.h.
Referenced by connectionLost(), and Mema::MemaProcessor::MemaProcessor().
onConnectionMade
std::function<void(int)> Mema::InterprocessConnectionImpl::onConnectionMade
Definition at line 45 of file InterprocessConnection.h.
Referenced by connectionMade().
onMessageReceived
std::function<void(int, const MemoryBlock&)> Mema::InterprocessConnectionImpl::onMessageReceived
Definition at line 47 of file InterprocessConnection.h.
Referenced by messageReceived().
The documentation for this class was generated from the following files:
Source/MemaProcessor/InterprocessConnection.h
Source/MemaProcessor/InterprocessConnection.cpp