Mema: Mema::ParameterListComponent Class Reference
Mema::ParameterListComponent Class Reference
#include <PluginControlComponent.h>
Public Member Functions
ParameterListComponent ()=default
~ParameterListComponent () override=default
void addRow (std::unique_ptr< ParameterRowComponent > row)
void layoutRows ()
std::vector< int > getDisplayOrder () const
ParameterRowComponent * getRowForParamIndex (int paramIdx)
void reorderRow (int fromParamIndex, int toParamIndex, bool insertBefore)
Detailed Description
list of ParameterRowComponents that acts as the DragAndDropContainer for row reordering.
Definition at line 307 of file PluginControlComponent.h.
Constructor & Destructor Documentation
ParameterListComponent()
Mema::ParameterListComponent::ParameterListComponent () default
~ParameterListComponent()
Mema::ParameterListComponent::~ParameterListComponent () override default
Member Function Documentation
addRow()
void Mema::ParameterListComponent::addRow (std::unique_ptr< ParameterRowComponent > row)
Definition at line 149 of file PluginControlComponent.cpp.
References layoutRows(), and reorderRow().
getDisplayOrder()
std::vector< int > Mema::ParameterListComponent::getDisplayOrder () const
Definition at line 166 of file PluginControlComponent.cpp.
getRowForParamIndex()
ParameterRowComponent * Mema::ParameterListComponent::getRowForParamIndex (int paramIdx)
Definition at line 175 of file PluginControlComponent.cpp.
layoutRows()
void Mema::ParameterListComponent::layoutRows ()
Definition at line 159 of file PluginControlComponent.cpp.
Referenced by addRow(), and reorderRow().
reorderRow()
void Mema::ParameterListComponent::reorderRow (int fromParamIndex, int toParamIndex, bool insertBefore)
Definition at line 183 of file PluginControlComponent.cpp.
References layoutRows().
Referenced by addRow().
The documentation for this class was generated from the following files:
Source/MemaProcessorEditor/PluginControlComponent.h
Source/MemaProcessorEditor/PluginControlComponent.cpp