Mema: Mema::ServiceData Struct Reference
Mema::ServiceData Struct Reference
#include <MemaServiceData.h>
Static Public Member Functions
static juce::String getServiceTypeUIDBase ()
Returns the base string for building service type UIDs.
static juce::String getMasterServiceTypeUID ()
Returns the UID for the Mema master (server) service.
static juce::String getMonitorServiceTypeUID ()
Returns the UID for the Mema.Mo monitor service.
static juce::String getRemoteServiceTypeUID ()
Returns the UID for the Mema.Re remote-control service.
static juce::String getServiceDescription ()
Returns the human-readable service description string.
static int getBroadcastPort ()
Returns the UDP port used for multicast service announcements.
static int getConnectionPort ()
Returns the TCP port used for client connections (55668).
Detailed Description
Definition at line 28 of file MemaServiceData.h.
Member Function Documentation
getBroadcastPort()
int Mema::ServiceData::getBroadcastPort () static
Returns the UDP port used for multicast service announcements.
Definition at line 44 of file MemaServiceData.cpp.
Referenced by Mema::MemaProcessor::MemaProcessor(), and MemaClientDiscoverComponent::setupServiceDiscovery().
getConnectionPort()
int Mema::ServiceData::getConnectionPort () static
Returns the TCP port used for client connections (55668).
Definition at line 49 of file MemaServiceData.cpp.
Referenced by Mema::MemaProcessor::MemaProcessor(), and MemaClientDiscoverComponent::setupServiceDiscovery().
getMasterServiceTypeUID()
juce::String Mema::ServiceData::getMasterServiceTypeUID () static
Returns the UID for the Mema master (server) service.
Definition at line 29 of file MemaServiceData.cpp.
References getServiceTypeUIDBase().
Referenced by Mema::MemaProcessor::MemaProcessor().
getMonitorServiceTypeUID()
juce::String Mema::ServiceData::getMonitorServiceTypeUID () static
Returns the UID for the Mema.Mo monitor service.
Definition at line 34 of file MemaServiceData.cpp.
References getServiceTypeUIDBase().
Referenced by MainComponent::MainComponent().
getRemoteServiceTypeUID()
juce::String Mema::ServiceData::getRemoteServiceTypeUID () static
Returns the UID for the Mema.Re remote-control service.
Definition at line 39 of file MemaServiceData.cpp.
References getServiceTypeUIDBase().
getServiceDescription()
static juce::String Mema::ServiceData::getServiceDescription () static
Returns the human-readable service description string.
getServiceTypeUIDBase()
juce::String Mema::ServiceData::getServiceTypeUIDBase () static
Returns the base string for building service type UIDs.
Definition at line 24 of file MemaServiceData.cpp.
Referenced by getMasterServiceTypeUID(), getMonitorServiceTypeUID(), getRemoteServiceTypeUID(), MainComponent::MainComponent(), and Mema::MemaProcessor::MemaProcessor().
The documentation for this struct was generated from the following files:
Source/MemaProcessor/MemaServiceData.h
Source/MemaProcessor/MemaServiceData.cpp