name: CI Mema.Re macOS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Mema.Re
        run: |
          cd Resources/Deployment/macOS
          chmod +x build_MemaRe_CI.sh
          ./build_MemaRe_CI.sh
